-- ============================================================
-- Quick fix: Seed the 5 empty tables + fix RLS for full app access
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- ============================================================

-- Fix RLS: allow anon full access to ALL tables (app uses anon key)
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT unnest(ARRAY[
      'profiles', 'brands', 'talents', 'partnerships', 'activities',
      'approval_items', 'outreach_sequences', 'outreach_emails', 'outreach_metrics',
      'marketplace_opportunities', 'opportunity_applications', 'deal_notes',
      'tasks', 'notifications', 'teams', 'team_members',
      'user_subscriptions', 'billing_history',
      'partnership_proposals', 'activation_checklists', 'planning_timelines'
    ])
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Allow all for authenticated" ON %I', tbl);
    EXECUTE format('DROP POLICY IF EXISTS "Allow read for anon" ON %I', tbl);
    EXECUTE format('DROP POLICY IF EXISTS "Allow all for anon" ON %I', tbl);
    EXECUTE format('CREATE POLICY "Allow all for authenticated" ON %I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    EXECUTE format('CREATE POLICY "Allow all for anon" ON %I FOR ALL TO anon USING (true) WITH CHECK (true)', tbl);
  END LOOP;
END $$;

-- Disable RLS on reference/lookup tables entirely
ALTER TABLE rate_benchmarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE platform_multipliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE category_premiums DISABLE ROW LEVEL SECURITY;
ALTER TABLE viewership_tiers DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE culture_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE mega_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE conferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE demographic_segments DISABLE ROW LEVEL SECURITY;
ALTER TABLE roi_benchmarks DISABLE ROW LEVEL SECURITY;
ALTER TABLE industry_guides DISABLE ROW LEVEL SECURITY;

-- CULTURE EVENTS (27 rows)
INSERT INTO culture_events (event_name, tier, category, subcategory, month, year, dates, location, audience_reach, best_industries, activation_opportunities, planning_lead_time, key_demographics, notes) VALUES
  ('Super Bowl LX',                '1', 'Sports',              'Football',          'February',  2026, 'Feb 8, 2026',             'New Orleans, LA',  '113M+ US viewers',       'Tech, Food & Beverage, Automotive, Entertainment', 'Watch parties, second-screen social campaigns, real-time commentary, halftime activations', '12-18 months', 'Mass market, 18-49, Sports fans',                    'NFL championship and biggest annual advertising event'),
  ('Black History Month',          '2', 'Cultural',            'Heritage',          'February',  2026, 'Feb 1-28, 2026',          'USA',              '45M+ engaged audience',  'Media, Fashion, Beauty, Education',                'Heritage storytelling, creator spotlights, brand commitments, educational content', '3-4 months', '18-35, Black American community, Gen Z',             'Annual recognition of Black history and culture'),
  ('Lunar New Year',               '2', 'Cultural',            'Heritage',          'February',  2026, 'Feb 17, 2026',            'Global',           '2B+ globally',           'Food & Beverage, Fashion, Beauty, Travel',         'Cultural celebration content, limited-edition products, family-focused campaigns', '3-4 months', 'Asian diaspora, AAPI community, Families',           'Celebration of the Lunar New Year across Asian cultures'),
  ('Ramadan',                      '2', 'Cultural',            'Religious',         'February',  2026, 'Feb 18 – Mar 19, 2026',   'Global',           '1.8B Muslims globally',  'Food & Beverage, Fashion, Beauty, Finance',        'Iftar partnerships, modest fashion, charity campaigns, community content', '4-6 months', 'Muslim community, MENA diaspora, All ages',          'Holy month of fasting, prayer and community for Muslims worldwide'),
  ('March Madness',                '1', 'Sports',              'Basketball',        'March',     2026, 'Mar 17 – Apr 6, 2026',    'USA',              '30M+ bracket participants', 'Sports, Food & Beverage, Tech, Entertainment',  'Bracket challenges, watch party content, campus activations, real-time social', '6-8 months', 'Sports fans, 18-34, College students',               'NCAA Division I basketball tournament — peak sports engagement window'),
  ('International Womens Day',     '2', 'Cultural',            'Awareness',         'March',     2026, 'Mar 8, 2026',             'Global',           '500M+ social impressions', 'Beauty, Fashion, Tech, Finance',                 'Women-led creator campaigns, brand commitments, empowerment content', '2-3 months', 'Women, Allies, Gen Z, Millennials',                  'Global celebration of women achievements and gender equality'),
  ('Earth Day',                    '2', 'Cultural',            'Awareness',         'April',     2026, 'Apr 22, 2026',            'Global',           '1B+ participants globally', 'Sustainability, Fashion, Food & Beverage, Tech', 'Sustainability pledges, eco-product launches, cleanup events, educational content', '3-4 months', 'Eco-conscious, Gen Z, Millennials, Families',        'Annual event promoting environmental protection and sustainability'),
  ('AAPI Heritage Month',          '2', 'Awareness Month',     'Heritage',          'May',       2026, 'May 1-31, 2026',          'USA',              '24M+ AAPI population',   'Beauty, Food & Beverage, Tech, Entertainment',    'AAPI creator spotlights, cultural storytelling, heritage brand collaborations', '3-4 months', 'AAPI community, Asian diaspora, All ages',           'Celebrating Asian American and Pacific Islander history and culture'),
  ('Mental Health Awareness Month','2', 'Awareness Month',     'Health',            'May',       2026, 'May 1-31, 2026',          'Global',           '500M+ social reach',     'Health, Wellness, Tech, Education',                'Mental health partnerships, creator vulnerability content, app integrations, resource sharing', '3-4 months', 'Gen Z, Millennials, Wellness community',             'Raising awareness for mental health education and advocacy'),
  ('Memorial Day',                 '3', 'Holiday/Civic',       'National',          'May',       2026, 'May 25, 2026',            'USA',              '40M+ engaged households', 'Retail, Food & Beverage, Travel, Automotive',     'Summer kickoff sales, outdoor content, patriotic campaigns, travel content', '2-3 months', 'Mass market, Families, Patriotic community',          'US federal holiday honoring military service members'),
  ('Pride Month',                  '1', 'Cultural',            'LGBTQ+',            'June',      2026, 'Jun 1-30, 2026',          'Global',           '500M+ global reach',     'Fashion, Beauty, Entertainment, Tech',             'Pride collections, LGBTQ+ creator spotlights, allyship campaigns, event sponsorships', '4-6 months', 'LGBTQ+, Allies, Gen Z, Millennials',                 'LGBTQ+ celebration, advocacy and visibility month'),
  ('Juneteenth',                   '2', 'Cultural',            'Heritage',          'June',      2026, 'Jun 19, 2026',            'USA',              '35M+ engaged audience',  'Media, Fashion, Beauty, Education',                'Heritage storytelling, Black creator spotlights, educational content, community events', '2-3 months', 'Black American community, All ages, Gen Z',          'Commemoration of the end of slavery in the United States'),
  ('NBA Finals',                   '1', 'Sports',              'Basketball',        'June',      2026, 'Jun 10-22, 2026',         'Global',           '15M+ US viewers per game', 'Sports, Fashion, Tech, Entertainment',           'Sneaker culture campaigns, watch party content, player partnerships, streetwear drops', '6-8 months', 'Sports fans, 18-34, Urban, Sneaker culture',         'NBA championship series — peak basketball engagement'),
  ('Fourth of July',               '2', 'Holiday/Civic',       'National',          'July',      2026, 'Jul 4, 2026',             'USA',              '300M+ US population',    'Food & Beverage, Retail, Travel, Entertainment',   'BBQ and outdoor content, patriotic campaigns, fireworks partnerships, summer product launches', '2-3 months', 'Mass market, Families, All ages',                    'US Independence Day celebrations'),
  ('Back to School',               '2', 'Holiday/Civic',       'Seasonal',          'August',    2026, 'Aug 1-31, 2026',          'USA',              '56M+ students, 50M+ parents', 'Tech, Fashion, Education, Retail',            'School supply campaigns, dorm room content, tech setup videos, fashion hauls', '3-4 months', 'Students, Parents, Teachers, Teens',                 'Annual back-to-school shopping and preparation season'),
  ('Hispanic Heritage Month',      '2', 'Cultural',            'Heritage',          'September', 2026, 'Sep 15 – Oct 15, 2026',   'USA',              '63M+ Hispanic Americans', 'Food & Beverage, Fashion, Beauty, Entertainment', 'Hispanic creator spotlights, cultural storytelling, bilingual content, Latinx brand collabs', '3-4 months', 'Hispanic/Latino community, Spanish speakers',        'Celebration of Hispanic and Latino American culture and contributions'),
  ('World Cup Qualifiers',         '1', 'Sports',              'Soccer',            'September', 2026, 'Sep-Nov 2026',            'Global',           '3.5B+ global audience',  'Sports, Fashion, Food & Beverage, Tech',           'Watch party content, jersey campaigns, cultural fusion activations, prediction contests', '6-12 months', 'Soccer fans, 18-45, Global, Multicultural',          'FIFA World Cup 2026 qualifying matches — building global excitement'),
  ('Halloween',                    '2', 'Holiday/Civic',       'Seasonal',          'October',   2026, 'Oct 31, 2026',            'USA',              '175M+ celebrating Americans', 'Fashion, Beauty, Entertainment, Food',         'Costume content, makeup tutorials, candy partnerships, spooky brand activations', '2-3 months', 'Gen Z, Millennials, Families, Teens',                'Annual costume, horror and fall celebration'),
  ('Diwali',                       '2', 'Cultural',            'Religious',         'October',   2026, 'Oct 20, 2026',            'Global',           '1.2B+ celebrants globally', 'Fashion, Beauty, Food & Beverage, Tech',        'Festival of lights content, traditional fashion, food celebrations, gifting campaigns', '3-4 months', 'South Asian diaspora, Hindu community, Families',    'Hindu festival of lights celebrated globally'),
  ('Veterans Day',                 '3', 'Holiday/Civic',       'National',          'November',  2026, 'Nov 11, 2026',            'USA',              '18M+ military families',  'Retail, Finance, Automotive, Travel',             'Military appreciation campaigns, veteran-owned business spotlights, patriotic content', '2-3 months', 'Mass market, Military community, Families',           'Honoring military veterans in the United States'),
  ('Thanksgiving',                 '2', 'Holiday/Civic',       'National',          'November',  2026, 'Nov 26, 2026',            'USA',              '330M+ US population',    'Food & Beverage, Retail, Travel, Home',            'Recipe content, family gathering campaigns, gratitude storytelling, travel partnerships', '3-4 months', 'Mass market, Families, Food community',               'US holiday for gratitude, family and food'),
  ('Black Friday / Cyber Monday',  '1', 'Holiday/Civic',       'Commercial',        'November',  2026, 'Nov 27-30, 2026',         'Global',           '$12B+ US online sales',  'All industries – peak shopping period',            'Deal roundups, unboxing content, live shopping streams, discount code partnerships', '4-6 months', 'Shoppers, 18-45, Deal seekers, Mass market',          'Largest annual shopping event — peak brand activation window'),
  ('Christmas / Holiday Season',   '1', 'Holiday/Civic',       'Religious/Seasonal','December',  2026, 'Dec 1-25, 2026',          'Global',           '2B+ celebrants globally', 'All industries – gifting season',                  'Gift guide content, holiday campaigns, advent calendars, family-focused activations', '6-12 months', 'Mass market, Families, All ages, Gift buyers',        'Global holiday season — gifting, family and year-end celebrations'),
  ('New Years Eve / Day',          '2', 'Holiday/Civic',       'Seasonal',          'December',  2026, 'Dec 31, 2026 – Jan 1, 2027', 'Global',       '4B+ global viewers',     'Fashion, Wellness, Finance, Entertainment',        'New year resolution campaigns, wellness launches, party content, goal-setting activations', '3-4 months', 'Mass market, All ages, Wellness community',           'Year-end celebration and new year resolutions season'),
  ('MLK Day 2027',                 '2', 'Cultural',            'Heritage',          'January',   2027, 'Jan 18, 2027',            'USA',              '45M+ engaged audience',  'Education, Media, Fashion, Non-profit',            'Service campaigns, educational content, social justice storytelling, community activations', '2-3 months', 'All ages, Black American community, Social justice',  'Honoring Martin Luther King Jr. and the civil rights movement'),
  ('Valentines Day 2027',          '2', 'Holiday/Civic',       'Seasonal',          'February',  2027, 'Feb 14, 2027',            'Global',           '$26B+ US spending',      'Fashion, Beauty, Food & Beverage, Jewelry',        'Gift guide content, couples campaigns, self-love activations, limited-edition drops', '2-3 months', 'Couples, 18-35, Gift buyers, Gen Z',                  'Celebration of love and relationships — key gifting and brand moment'),
  ('Womens History Month 2027',    '2', 'Awareness Month',     'Heritage',          'March',     2027, 'Mar 1-31, 2027',          'Global',           '500M+ social reach',     'Beauty, Fashion, Tech, Finance, Education',        'Women creator spotlights, brand commitments, mentorship content, empowerment campaigns', '3-4 months', 'Women, Allies, Gen Z, Millennials',                   'Celebrating the contributions and achievements of women')
ON CONFLICT DO NOTHING;

-- MEGA EVENTS (10 rows)
INSERT INTO mega_events (event_name, dates, location, notes, global_reach, format_details, planning_urgency, year, key_facts, tier) VALUES
  ('FIFA World Cup 2026',     'Jun 11 – Jul 19, 2026', 'USA / Mexico / Canada', 'First tri-nation World Cup — largest sporting event globally', '5B+ cumulative TV viewers, 5.4M in-person attendance', 'Multi-city tournament, 48 teams, 80 matches over 39 days', 'CRITICAL — activation windows closing Q1 2026', 2026, '16 host cities, first 48-team format, $11B economic impact projected', '1'),
  ('Olympics 2028 (LA)',       'Jul 14-30, 2028',       'Los Angeles, CA',       'Summer Olympic Games — early brand activation planning window', '4B+ global TV viewers, 4M in-person attendance', 'Multi-sport, 32 sports, 329 events over 17 days', 'EARLY PLANNING — partnerships opening 2026', 2028, 'First LA Olympics since 1984, $7B budget, 800+ events across SoCal', '1'),
  ('Coachella 2026',           'Apr 10-19, 2026',       'Indio, CA',             'Premier music and arts festival in the California desert', '250K+ attendees, 40M+ social impressions', '2 weekends, 6 stages, 150+ artists, brand activations throughout grounds', 'HIGH — brand house applications due Dec 2025', 2026, 'Top festival for influencer marketing, 90% of attendees post on social', '1'),
  ('SXSW 2026',               'Mar 13-22, 2026',       'Austin, TX',            'South by Southwest — converging tech, film and music', '300K+ attendees, 100M+ social impressions', '10-day festival, film premieres, music showcases, tech panels, brand houses', 'HIGH — panel submissions due Oct 2025', 2026, 'Premier platform for product launches, 2,000+ sessions, 800+ speakers', '1'),
  ('ComplexCon 2026',          'Nov 7-8, 2026',         'Long Beach, CA',        'Culture, fashion, music and sneaker convention', '60K+ attendees, 200M+ social impressions', '2-day convention, brand booths, exclusive drops, performances, panels', 'MEDIUM — booth applications due Jul 2026', 2026, 'Top event for streetwear and sneaker culture, 200+ brands exhibit', '1'),
  ('Met Gala 2026',            'May 4, 2026',           'New York, NY',          'Annual fundraising gala for the Met Costume Institute', '700 attendees, 1B+ social impressions globally', 'Single evening event, celebrity red carpet, exclusive invite-only', 'HIGH — fashion brand alignment critical', 2026, 'Most-discussed fashion event globally, red carpet drives 30M+ social posts', '1'),
  ('Grammy Awards 2026',       'Feb 1, 2026',           'Los Angeles, CA',       'Annual music industry awards ceremony', '18K venue, 12M+ US TV viewers, 500M+ social reach', 'Live broadcast, performances, red carpet, after-parties', 'HIGH — sponsorship packages close Nov 2025', 2026, '67th ceremony, music industry benchmark, second-screen engagement peak', '1'),
  ('VidCon 2026',              'Jun 25-28, 2026',       'Anaheim, CA',           'Largest global creator economy convention', '75K+ attendees, 100M+ social impressions', '4-day event, creator meetups, brand activations, industry track, featured creator stage', 'MEDIUM — brand activation apps due Mar 2026', 2026, 'Premier event for connecting with creators and fans, 500+ creators attend', '1'),
  ('New York Fashion Week',    'Sep 9-14, 2026',        'New York, NY',          'Bi-annual fashion event showcasing designer collections', '200K+ in-person, 500M+ social impressions', '6-day event, runway shows, presentations, pop-ups, street style coverage', 'HIGH — front row partnerships close Jun 2026', 2026, 'Sets global fashion trends, 300+ shows and presentations', '1'),
  ('Art Basel Miami 2026',     'Dec 3-7, 2026',         'Miami Beach, FL',       'International art fair combining art, culture and luxury', '83K+ attendees, 200M+ social impressions', '5-day fair, gallery exhibitions, satellite events, brand activations, parties', 'MEDIUM — booth applications due Aug 2026', 2026, 'Intersection of art, luxury and culture, 280+ galleries exhibit', '1')
ON CONFLICT DO NOTHING;

-- CONFERENCES (10 rows)
INSERT INTO conferences (conference_name, industry_focus, typical_date, location, attendees, sponsorship_range, why_attend, key_audience, best_for_industries, event_name, category, notes, dates) VALUES
  ('VidSummit 2026',               'Creator Economy',       'September 2026', 'Dallas, TX',        '3,000+',   '$15K–$50K',  'Premier creator growth conference — learn YouTube strategy, monetization and audience building from top creators', 'YouTube creators, brand marketers, agencies', 'Tech, Entertainment, Education', 'VidSummit 2026', 'Creator Economy', 'Premier creator economy and YouTube growth conference', 'Sep 20-22, 2026'),
  ('Social Media Marketing World',  'Marketing',            'March 2026',     'San Diego, CA',     '5,000+',   '$25K–$75K',  'Largest social media marketing conference — cutting-edge tactics from 100+ expert speakers', 'Social media managers, brand marketers, CMOs', 'All industries', 'Social Media Marketing World', 'Marketing', 'Leading social media marketing conference', 'Mar 15-17, 2026'),
  ('CES 2026',                     'Technology',            'January 2026',   'Las Vegas, NV',     '115,000+', '$50K–$250K', 'World''s largest consumer tech exhibition — first look at products that define the year ahead', 'Tech executives, product managers, media', 'Tech, Automotive, Health, Entertainment', 'CES 2026', 'Technology', 'Consumer Electronics Show', 'Jan 6-9, 2026'),
  ('Cannes Lions 2026',            'Advertising',           'June 2026',      'Cannes, France',    '12,000+',  '$40K–$200K', 'Global creativity festival — benchmark campaigns, network with top agency and brand leaders', 'CMOs, creative directors, agency leaders', 'Advertising, Entertainment, Tech', 'Cannes Lions 2026', 'Advertising', 'International Festival of Creativity', 'Jun 15-19, 2026'),
  ('TwitchCon 2026',               'Gaming / Streaming',    'September 2026', 'San Diego, CA',     '35,000+',  '$25K–$100K', 'Official Twitch convention — connect with streamers, fans and gaming brands in the live streaming ecosystem', 'Streamers, gaming brands, esports teams', 'Gaming, Tech, Entertainment, Food & Beverage', 'TwitchCon 2026', 'Gaming / Streaming', 'Official Twitch community convention', 'Sep 26-28, 2026'),
  ('Advertising Week NY',          'Advertising',           'October 2026',   'New York, NY',      '20,000+',  '$30K–$100K', 'Thought leadership summit — panels on the future of advertising, marketing technology and brand strategy', 'Brand marketers, agency leaders, media buyers', 'Advertising, Tech, Media, Finance', 'Advertising Week NY', 'Advertising', 'Thought leadership summit for advertising', 'Oct 13-16, 2026'),
  ('Influencer Marketing Show',    'Influencer Marketing',  'May 2026',       'New York, NY',      '1,500+',   '$10K–$40K',  'Dedicated influencer marketing conference — ROI measurement, creator partnerships and campaign strategy', 'Brand marketers, agency managers, creators', 'Beauty, Fashion, Food & Beverage, Tech', 'Influencer Marketing Show', 'Influencer Marketing', 'Dedicated influencer marketing conference', 'May 10-11, 2026'),
  ('Creator Economy Expo',         'Creator Economy',       'May 2026',       'Cleveland, OH',     '2,500+',   '$12K–$40K',  'Business of content creation — monetization strategies, platform diversification and building sustainable creator businesses', 'Full-time creators, aspiring creators, agencies', 'Creator Economy, Tech, Education', 'Creator Economy Expo', 'Creator Economy', 'Conference focused on business of content creation', 'May 4-6, 2026'),
  ('Brand Innovation Summit',      'Brand Marketing',       'July 2026',      'Chicago, IL',       '2,000+',   '$15K–$50K',  'Brand partnership and innovation strategy — learn from Fortune 500 brand leaders and disruptive DTC brands', 'Brand managers, partnership leads, CMOs', 'All industries, especially Retail and CPG', 'Brand Innovation Summit', 'Brand Marketing', 'Brand partnership and innovation strategy conference', 'Jul 22-23, 2026'),
  ('SMMW Creators Track',          'Creator Economy',       'March 2026',     'San Diego, CA',     '1,200+',   '$8K–$25K',   'Dedicated creator monetisation track — YouTube, TikTok and Instagram growth strategies from practitioners', 'Content creators, social media managers', 'Creator Economy, Entertainment, Education', 'SMMW Creators Track', 'Creator Economy', 'Dedicated creator monetisation track at SMMW', 'Mar 16-17, 2026')
ON CONFLICT DO NOTHING;

-- DEMOGRAPHIC SEGMENTS (8 rows)
INSERT INTO demographic_segments (name, description, age_range, gender, interests, population_size, buying_power, media_preferences, top_events, key_cultural_moments, brand_activation_tips, activation_tips) VALUES
  ('Gen Z Trendsetters',     'Fashion and culture-forward Gen Z digital natives',  '18-26', 'all',         '["fashion","music","gaming","social justice","sustainability"]', '68M (US)', '$360B annual spending', 'TikTok, Instagram Reels, YouTube Shorts, Snapchat — short-form video dominant, meme culture, authentic UGC', 'Coachella, ComplexCon, Pride Month, Halloween, Black Friday', 'Pride Month, Earth Day, Mental Health Awareness, Black History Month', 'Lead with authenticity over polish. Co-create with creators rather than scripting. Use TikTok challenges and AR filters. Values-driven messaging converts.', 'Use TikTok and Instagram Reels. Co-create campaigns. Prioritise values-driven messaging.'),
  ('Millennial Parents',     'Millennial parents balancing family and career',      '30-40', 'all',         '["parenting","home","health","finance","education"]', '45M (US)', '$2.5T household spending', 'Instagram, Facebook, YouTube, Pinterest — researching purchases, family content, educational videos', 'Back to School, Thanksgiving, Christmas, Memorial Day, Fourth of July', 'Back to School, Thanksgiving, Christmas, Mental Health Awareness', 'Relatable parenting content converts. Product integrations in daily routines. Educational content for kids. Family-friendly unboxing and reviews.', 'Create relatable family content. Integrate products into daily routines. Family-friendly reviews.'),
  ('Fitness Enthusiasts',    'Dedicated health and fitness consumers',              '22-38', 'all',         '["fitness","nutrition","wellness","sports","outdoor"]', '32M (US)', '$1.2T wellness economy', 'Instagram, TikTok, YouTube — workout videos, transformation stories, supplement and gear reviews', 'Super Bowl, March Madness, Olympics, World Cup, Back to School', 'New Year (resolutions), Summer prep, Mental Health Awareness', 'Challenge-based campaigns drive participation. Partner with certified trainers. Transformation content converts. Ambassador programs over one-off posts.', 'Run 30-day challenges. Partner with certified trainers. Use before/after transformation content.'),
  ('Tech Early Adopters',    'Technology enthusiasts who adopt before mainstream',   '25-45', 'male_skew',   '["technology","gaming","productivity","AI","gadgets"]', '18M (US)', '$800B annual tech spending', 'YouTube (long-form reviews), Twitter/X, LinkedIn, Reddit — deep-dive reviews, comparison content, tech forums', 'CES, SXSW, VidCon, Apple Events, Black Friday/Cyber Monday', 'CES week, product launch cycles, Back to School tech', 'Detailed unboxing and review content. Comparison and versus formats. Early access exclusives build excitement. Data-driven talking points for authenticity.', 'Invest in detailed YouTube reviews. Provide early exclusive access. Use comparison formats.'),
  ('Beauty Conscious',       'Beauty and personal care focused consumers',           '16-35', 'female_skew', '["beauty","skincare","fashion","wellness","self-care"]', '55M (US)', '$580B global beauty market', 'Instagram, TikTok, YouTube — GRWM content, tutorials, product reviews, routine-based formats', 'Met Gala, NYFW, Coachella, Valentines Day, Pride Month', 'Pride Month, Valentines Day, International Womens Day, Diwali', 'GRWM and routine-based content outperforms scripted ads. Partner with creators who organically use similar products. TikTok for discovery, Instagram for conversion.', 'Prioritise GRWM content. Let creators choose products. TikTok for discovery, IG for conversion.'),
  ('Gen Alpha Influence',    'Parents purchasing on behalf of Gen Alpha (2010-2025)', '0-15',  'all',        '["toys","gaming","education","entertainment","kids content"]', '48M (US)', '$500B+ influenced spending', 'YouTube, TikTok, Roblox — kids content, gaming, educational videos, family channels', 'Back to School, Christmas, Halloween, Summer Break', 'Christmas, Back to School, Halloween, Summer Break', 'Family-friendly unboxing and educational content. Partner through parent-approved channels. YouTube Kids and TikTok safety-first approach. Toy and game reviews drive purchase intent.', 'Use family-friendly unboxing. Partner with parent-approved channels. YouTube Kids safety-first.'),
  ('Affluent Professionals', 'High-income professionals with discretionary spending', '35-55', 'all',        '["finance","luxury","travel","business","wellness"]', '22M (US)', '$3.4T combined income', 'LinkedIn, YouTube, Instagram, Twitter/X — thought leadership, premium reviews, travel content, business insights', 'Art Basel, NYFW, Cannes Lions, CES, Advertising Week', 'Tax season, year-end giving, summer travel, holiday luxury gifting', 'Thought-leadership content over influencer marketing. LinkedIn posts perform well. Premium product reviews with expertise. Quality over trends in messaging.', 'Use thought leadership on LinkedIn. Expertise-driven premium reviews. Quality over trend messaging.'),
  ('Multicultural Gen Z',    'Hispanic, Black, AAPI Gen Z consumers shaping culture', '18-28', 'all',       '["music","fashion","food","culture","social justice","gaming"]', '42M (US)', '$600B+ combined spending', 'TikTok, Instagram, YouTube, Snapchat — culturally authentic content, bilingual creators, social commerce', 'Pride Month, Juneteenth, Hispanic Heritage Month, Lunar New Year, Diwali', 'Black History Month, AAPI Heritage, Hispanic Heritage, Lunar New Year, Juneteenth, Ramadan', 'Culturally authentic storytelling is non-negotiable. Bilingual content expands reach. Community-first campaigns build loyalty. Social commerce converts.', 'Lead with cultural authenticity. Use bilingual content. Community-first campaigns build loyalty.')
ON CONFLICT DO NOTHING;

-- INDUSTRY GUIDES (8 rows)
INSERT INTO industry_guides (title, industry, content, sector, budget_allocation, priority_tier_1_events, tier_2_events, heritage_awareness_months, key_conferences, best_demographics, activation_strategies) VALUES
  ('Beauty & Skincare Creator Partnerships', 'Beauty & Personal Care', 'The beauty industry leads in influencer marketing spend with the highest ROI from micro and mid-tier creators using GRWM and routine-based content.', 'Skincare, Cosmetics, Personal Care', '$50K–$250K per campaign', 'Met Gala, NYFW, Coachella, Pride Month', 'Valentines Day, International Womens Day, Diwali, Black Friday', 'Womens History Month, Pride Month, AAPI Heritage Month, Hispanic Heritage Month', 'Influencer Marketing Show, SMMW, Cannes Lions', 'Beauty Conscious, Gen Z Trendsetters, Multicultural Gen Z', 'Prioritise GRWM and routine-format content. Partner with creators who organically use similar products. Allow 4-6 weeks for seeding. Offer affiliate codes alongside flat fees. TikTok for discovery, Instagram for conversion.'),
  ('Tech Product Launch Playbook', 'Technology', 'Tech brands see highest ROI with YouTube integrations and detailed review content. Trust is paramount — creators must genuinely evaluate products.', 'Consumer Electronics, Software, SaaS', '$75K–$500K per launch', 'CES, SXSW, Apple Events, Black Friday/Cyber Monday', 'Back to School, VidCon, Product Launch Windows', 'None — focus on product launch cycles and seasonal demand', 'CES, SXSW, VidSummit, Creator Economy Expo', 'Tech Early Adopters, Affluent Professionals, Gen Z Trendsetters', 'Invest in long-form YouTube reviews over short social posts. Provide early exclusive access. Use comparison and versus content. Run campaigns around CES and launch cycles. Data-driven talking points for authenticity.'),
  ('Fitness & Wellness Brand Guide', 'Sports & Fitness', 'Fitness creators command high trust and engagement. Challenge-based campaigns drive participation and UGC at massive scale.', 'Equipment, Apparel, Supplements, Wellness', '$40K–$200K per campaign', 'Super Bowl, Olympics, World Cup, March Madness', 'New Year Resolutions, Summer Prep, Back to School, Mental Health Awareness Month', 'Mental Health Awareness Month (May)', 'VidSummit, SMMW, Brand Innovation Summit', 'Fitness Enthusiasts, Gen Z Trendsetters, Millennial Parents', 'Run 30-day challenge campaigns for maximum UGC. Partner with certified trainers for supplement credibility. Use Instagram Reels and TikTok for workout content. Invest in ambassador programs over one-off posts. Time around New Year and summer.'),
  ('Food & Beverage Creator Strategy', 'Food & Beverage', 'Food content performs exceptionally on TikTok and Instagram. Authentic recipe integrations outperform scripted ads by 3x.', 'CPG, Restaurants, Meal Delivery, Beverages', '$25K–$150K per campaign', 'Super Bowl (ads), Thanksgiving, Black Friday, World Cup watch parties', 'Memorial Day (BBQ), Fourth of July, Back to School lunches, Halloween', 'Hispanic Heritage Month, Lunar New Year, Ramadan (Iftar), Diwali', 'SMMW, Brand Innovation Summit, Influencer Marketing Show', 'Millennial Parents, Fitness Enthusiasts, Multicultural Gen Z', 'Use recipe integration format over product-only showcases. Partner with micro food bloggers for highest engagement. Leverage TikTok recipe trends. Run seasonal campaigns tied to holidays and cultural food moments. Genuine reactions only.'),
  ('Fashion & Apparel Partnership Guide', 'Fashion & Apparel', 'Fashion thrives on visual platforms. Haul, try-on and styling content converts at the highest rates. Diversity directly correlates with reach.', 'Streetwear, Luxury, Athleisure, DTC', '$50K–$300K per campaign', 'NYFW, Met Gala, Coachella, ComplexCon, Black Friday', 'Pride Month, Back to School, Halloween, Valentines Day', 'Black History Month, Pride Month, Hispanic Heritage Month, AAPI Heritage Month', 'ComplexCon, NYFW events, Cannes Lions, Advertising Week', 'Gen Z Trendsetters, Beauty Conscious, Multicultural Gen Z', 'Invest in try-on haul and styling content over static shots. Cast diverse creators for maximum reach. Time campaigns around fashion weeks and seasonal drops. Offer exclusive early-access through creators. Enable social commerce with shoppable links.'),
  ('Gaming & Esports Activation Guide', 'Gaming', 'Gaming creators offer unmatched live engagement on Twitch and YouTube. Non-endemic brands increasingly activate as the audience matures.', 'Game Publishers, Hardware, Esports, Non-endemic', '$40K–$250K per campaign', 'TwitchCon, E3/Summer Game Fest, The Game Awards, ComplexCon', 'Major game launches, Esports tournaments, Back to School, Black Friday', 'None — focus on game release calendars and esports schedules', 'TwitchCon, CES (gaming), VidSummit, Creator Economy Expo', 'Tech Early Adopters, Gen Z Trendsetters, Gen Alpha Influence', 'Use Twitch integrations and live stream sponsorships for real-time engagement. YouTube gaming for evergreen content. Non-endemic brands lead with creator authenticity. Run campaigns around major game launches. Enable creator codes and in-game items.'),
  ('Finance & Fintech Creator Compliance Guide', 'Finance & Fintech', 'Finance content requires careful compliance navigation but delivers high CLV. Educational content on YouTube and LinkedIn performs best.', 'Banking, Insurance, Fintech, Crypto, Investing', '$50K–$300K per campaign', 'Tax Season (Jan-Apr), Year-End Financial Planning, Black Friday (financial products)', 'Back to School (student finance), New Year (budgeting resolutions)', 'None — focus on financial planning seasonal cycles', 'Cannes Lions, Advertising Week, Brand Innovation Summit', 'Affluent Professionals, Tech Early Adopters, Millennial Parents', 'Work with creators who have demonstrated financial literacy. Ensure all content passes compliance review. Favour educational explainer content. Use LinkedIn alongside YouTube for B2B fintech. Provide clear disclosure templates and approved talking points.'),
  ('Travel & Hospitality Creator Playbook', 'Travel & Hospitality', 'Travel content has strong long-tail value — destination videos drive bookings months after publication. Instagram and YouTube are primary platforms.', 'Hotels, Airlines, Tourism Boards, OTAs', '$30K–$200K per campaign', 'Summer Travel Season (Jun-Aug), Spring Break, Holiday Travel, Art Basel Miami', 'Memorial Day, Fourth of July, Thanksgiving travel, Valentines Day getaways', 'None — focus on booking windows and travel seasons', 'SXSW (travel tech), Cannes Lions, Advertising Week', 'Affluent Professionals, Millennial Parents, Gen Z Trendsetters', 'Invest in YouTube destination guides for long-tail search value. Instagram Reels for aspirational visual content. Partner for hosted trips with clear deliverables. Time around booking windows: January, spring break and summer. Enable booking links with tracked attribution.')
ON CONFLICT DO NOTHING;

-- Verify
SELECT 'rate_benchmarks' AS tbl, COUNT(*) FROM rate_benchmarks
UNION ALL SELECT 'platform_multipliers', COUNT(*) FROM platform_multipliers
UNION ALL SELECT 'category_premiums', COUNT(*) FROM category_premiums
UNION ALL SELECT 'viewership_tiers', COUNT(*) FROM viewership_tiers
UNION ALL SELECT 'subscription_plans', COUNT(*) FROM subscription_plans
UNION ALL SELECT 'culture_events', COUNT(*) FROM culture_events
UNION ALL SELECT 'mega_events', COUNT(*) FROM mega_events
UNION ALL SELECT 'conferences', COUNT(*) FROM conferences
UNION ALL SELECT 'demographic_segments', COUNT(*) FROM demographic_segments
UNION ALL SELECT 'roi_benchmarks', COUNT(*) FROM roi_benchmarks
UNION ALL SELECT 'industry_guides', COUNT(*) FROM industry_guides;
