/**
 * Curated list of real brands organized by industry.
 * Each brand is known to actively work with influencers/creators.
 * Mix of enterprise, mid-market, and up-and-coming brands.
 *
 * 48 industries x 25 brands = 1,200 brands total.
 */

export const BRAND_LIST: Record<string, Array<{ name: string; domain: string }>> = {

  fashion: [
    { name: "Nike", domain: "nike.com" },
    { name: "Adidas", domain: "adidas.com" },
    { name: "Zara", domain: "zara.com" },
    { name: "H&M", domain: "hm.com" },
    { name: "SHEIN", domain: "shein.com" },
    { name: "Revolve", domain: "revolve.com" },
    { name: "Fashion Nova", domain: "fashionnova.com" },
    { name: "ASOS", domain: "asos.com" },
    { name: "PrettyLittleThing", domain: "prettylittlething.com" },
    { name: "Skims", domain: "skims.com" },
    { name: "Reformation", domain: "thereformation.com" },
    { name: "Everlane", domain: "everlane.com" },
    { name: "Lululemon", domain: "lululemon.com" },
    { name: "Free People", domain: "freepeople.com" },
    { name: "Anthropologie", domain: "anthropologie.com" },
    { name: "Nordstrom", domain: "nordstrom.com" },
    { name: "Uniqlo", domain: "uniqlo.com" },
    { name: "Boohoo", domain: "boohoo.com" },
    { name: "Missguided", domain: "missguided.com" },
    { name: "Princess Polly", domain: "princesspolly.com" },
    { name: "Mango", domain: "mango.com" },
    { name: "Abercrombie & Fitch", domain: "abercrombie.com" },
    { name: "Urban Outfitters", domain: "urbanoutfitters.com" },
    { name: "Gymshark", domain: "gymshark.com" },
    { name: "Alo Yoga", domain: "aloyoga.com" },
  ],

  beauty: [
    { name: "Sephora", domain: "sephora.com" },
    { name: "Glossier", domain: "glossier.com" },
    { name: "Fenty Beauty", domain: "fentybeauty.com" },
    { name: "Charlotte Tilbury", domain: "charlottetilbury.com" },
    { name: "Rare Beauty", domain: "rarebeauty.com" },
    { name: "MAC Cosmetics", domain: "maccosmetics.com" },
    { name: "NARS", domain: "narscosmetics.com" },
    { name: "Too Faced", domain: "toofaced.com" },
    { name: "Tarte Cosmetics", domain: "tartecosmetics.com" },
    { name: "Benefit Cosmetics", domain: "benefitcosmetics.com" },
    { name: "Morphe", domain: "morphe.com" },
    { name: "ColourPop", domain: "colourpop.com" },
    { name: "NYX Professional Makeup", domain: "nyxcosmetics.com" },
    { name: "Maybelline", domain: "maybelline.com" },
    { name: "Urban Decay", domain: "urbandecay.com" },
    { name: "Tatcha", domain: "tatcha.com" },
    { name: "Milk Makeup", domain: "milkmakeup.com" },
    { name: "Ilia Beauty", domain: "iliabeauty.com" },
    { name: "Patrick Ta", domain: "patrickta.com" },
    { name: "Kosas", domain: "kfrancisbeauty.com" },
    { name: "Anastasia Beverly Hills", domain: "anastasiabeverlyhills.com" },
    { name: "Hourglass", domain: "hourglasscosmetics.com" },
    { name: "Laura Mercier", domain: "lauramercier.com" },
    { name: "e.l.f. Cosmetics", domain: "elfcosmetics.com" },
    { name: "Huda Beauty", domain: "hudabeauty.com" },
  ],

  tech: [
    { name: "Apple", domain: "apple.com" },
    { name: "Samsung", domain: "samsung.com" },
    { name: "Google", domain: "google.com" },
    { name: "Microsoft", domain: "microsoft.com" },
    { name: "Sony", domain: "sony.com" },
    { name: "Dell", domain: "dell.com" },
    { name: "HP", domain: "hp.com" },
    { name: "Lenovo", domain: "lenovo.com" },
    { name: "OnePlus", domain: "oneplus.com" },
    { name: "Nothing", domain: "nothing.tech" },
    { name: "Anker", domain: "anker.com" },
    { name: "Razer", domain: "razer.com" },
    { name: "Logitech", domain: "logitech.com" },
    { name: "Bose", domain: "bose.com" },
    { name: "Sonos", domain: "sonos.com" },
    { name: "DJI", domain: "dji.com" },
    { name: "GoPro", domain: "gopro.com" },
    { name: "Ring", domain: "ring.com" },
    { name: "Dyson", domain: "dyson.com" },
    { name: "Asus", domain: "asus.com" },
    { name: "Beats by Dre", domain: "beatsbydre.com" },
    { name: "JBL", domain: "jbl.com" },
    { name: "Nvidia", domain: "nvidia.com" },
    { name: "Intel", domain: "intel.com" },
    { name: "Corsair", domain: "corsair.com" },
  ],

  fitness: [
    { name: "Peloton", domain: "onepeloton.com" },
    { name: "Gymshark", domain: "gymshark.com" },
    { name: "Athletic Greens", domain: "athleticgreens.com" },
    { name: "Whoop", domain: "whoop.com" },
    { name: "Fitbit", domain: "fitbit.com" },
    { name: "MyFitnessPal", domain: "myfitnesspal.com" },
    { name: "Alo Yoga", domain: "aloyoga.com" },
    { name: "Lululemon", domain: "lululemon.com" },
    { name: "Tonal", domain: "tonal.com" },
    { name: "Mirror", domain: "mirror.co" },
    { name: "Hydrow", domain: "hydrow.com" },
    { name: "NordicTrack", domain: "nordictrack.com" },
    { name: "Bowflex", domain: "bowflex.com" },
    { name: "Hyperice", domain: "hyperice.com" },
    { name: "Theragun", domain: "therabody.com" },
    { name: "Nobull", domain: "nobullproject.com" },
    { name: "Vuori", domain: "vuoriclothing.com" },
    { name: "Fabletics", domain: "fabletics.com" },
    { name: "Under Armour", domain: "underarmour.com" },
    { name: "Celsius", domain: "celsius.com" },
    { name: "Optimum Nutrition", domain: "optimumnutrition.com" },
    { name: "Ghost Lifestyle", domain: "ghostlifestyle.com" },
    { name: "1st Phorm", domain: "1stphorm.com" },
    { name: "Transparent Labs", domain: "transparentlabs.com" },
    { name: "Beam", domain: "beamtlc.com" },
  ],

  food: [
    { name: "HelloFresh", domain: "hellofresh.com" },
    { name: "Blue Apron", domain: "blueapron.com" },
    { name: "DoorDash", domain: "doordash.com" },
    { name: "Uber Eats", domain: "ubereats.com" },
    { name: "Grubhub", domain: "grubhub.com" },
    { name: "Factor", domain: "factor75.com" },
    { name: "Daily Harvest", domain: "dailyharvest.com" },
    { name: "Thrive Market", domain: "thrivemarket.com" },
    { name: "Hungryroot", domain: "hungryroot.com" },
    { name: "ButcherBox", domain: "butcherbox.com" },
    { name: "Impossible Foods", domain: "impossiblefoods.com" },
    { name: "Beyond Meat", domain: "beyondmeat.com" },
    { name: "Chomps", domain: "chomps.com" },
    { name: "Magic Spoon", domain: "magicspoon.com" },
    { name: "Liquid Death", domain: "liquiddeath.com" },
    { name: "Olipop", domain: "drinkolipop.com" },
    { name: "Partake Foods", domain: "partakefoods.com" },
    { name: "Siete Foods", domain: "sietefoods.com" },
    { name: "Hu Kitchen", domain: "hukitchen.com" },
    { name: "RXBAR", domain: "rxbar.com" },
    { name: "Kind Snacks", domain: "kindsnacks.com" },
    { name: "Kodiak Cakes", domain: "kodiakcakes.com" },
    { name: "Daring Foods", domain: "daringfoods.com" },
    { name: "Poppi", domain: "drinkpoppi.com" },
    { name: "Sakara Life", domain: "sakara.com" },
  ],

  travel: [
    { name: "Airbnb", domain: "airbnb.com" },
    { name: "Booking.com", domain: "booking.com" },
    { name: "Expedia", domain: "expedia.com" },
    { name: "Tripadvisor", domain: "tripadvisor.com" },
    { name: "Marriott", domain: "marriott.com" },
    { name: "Hilton", domain: "hilton.com" },
    { name: "Hyatt", domain: "hyatt.com" },
    { name: "Vrbo", domain: "vrbo.com" },
    { name: "Hopper", domain: "hopper.com" },
    { name: "Kayak", domain: "kayak.com" },
    { name: "Viator", domain: "viator.com" },
    { name: "GetYourGuide", domain: "getyourguide.com" },
    { name: "Contiki", domain: "contiki.com" },
    { name: "G Adventures", domain: "gadventures.com" },
    { name: "Intrepid Travel", domain: "intrepidtravel.com" },
    { name: "Away Travel", domain: "awaytravel.com" },
    { name: "Samsonite", domain: "samsonite.com" },
    { name: "Beis Travel", domain: "beistravel.com" },
    { name: "Scott's Cheap Flights", domain: "going.com" },
    { name: "Hostelworld", domain: "hostelworld.com" },
    { name: "Sonder", domain: "sonder.com" },
    { name: "Four Seasons", domain: "fourseasons.com" },
    { name: "IHG", domain: "ihg.com" },
    { name: "Selina", domain: "selina.com" },
    { name: "Wanderlog", domain: "wanderlog.com" },
  ],

  gaming: [
    { name: "Razer", domain: "razer.com" },
    { name: "SteelSeries", domain: "steelseries.com" },
    { name: "HyperX", domain: "hyperx.com" },
    { name: "Corsair", domain: "corsair.com" },
    { name: "Xbox", domain: "xbox.com" },
    { name: "PlayStation", domain: "playstation.com" },
    { name: "Nintendo", domain: "nintendo.com" },
    { name: "Epic Games", domain: "epicgames.com" },
    { name: "Riot Games", domain: "riotgames.com" },
    { name: "Electronic Arts", domain: "ea.com" },
    { name: "Ubisoft", domain: "ubisoft.com" },
    { name: "Activision Blizzard", domain: "activisionblizzard.com" },
    { name: "NZXT", domain: "nzxt.com" },
    { name: "Secretlab", domain: "secretlab.co" },
    { name: "Elgato", domain: "elgato.com" },
    { name: "Scuf Gaming", domain: "scufgaming.com" },
    { name: "MSI", domain: "msi.com" },
    { name: "Astro Gaming", domain: "astrogaming.com" },
    { name: "G Fuel", domain: "gfuel.com" },
    { name: "Turtle Beach", domain: "turtlebeach.com" },
    { name: "Alienware", domain: "alienware.com" },
    { name: "Roccat", domain: "roccat.com" },
    { name: "Roblox", domain: "roblox.com" },
    { name: "Discord", domain: "discord.com" },
    { name: "Steam", domain: "store.steampowered.com" },
  ],

  lifestyle: [
    { name: "Target", domain: "target.com" },
    { name: "Amazon", domain: "amazon.com" },
    { name: "Anthropologie", domain: "anthropologie.com" },
    { name: "West Elm", domain: "westelm.com" },
    { name: "Pottery Barn", domain: "potterybarn.com" },
    { name: "Crate & Barrel", domain: "crateandbarrel.com" },
    { name: "CB2", domain: "cb2.com" },
    { name: "Article", domain: "article.com" },
    { name: "Brooklinen", domain: "brooklinen.com" },
    { name: "Parachute Home", domain: "parachutehome.com" },
    { name: "Casper", domain: "casper.com" },
    { name: "Saatva", domain: "saatva.com" },
    { name: "Our Place", domain: "fromourplace.com" },
    { name: "Great Jones", domain: "greatjonesgoods.com" },
    { name: "Caraway Home", domain: "carawayhome.com" },
    { name: "Brightland", domain: "brightland.co" },
    { name: "Material Kitchen", domain: "materialkitchen.com" },
    { name: "Buffy", domain: "buffy.co" },
    { name: "Sunday Riley", domain: "sundayriley.com" },
    { name: "Supergoop", domain: "supergoop.com" },
    { name: "Stanley", domain: "stanley1913.com" },
    { name: "Yeti", domain: "yeti.com" },
    { name: "HydroFlask", domain: "hydroflask.com" },
    { name: "Rifle Paper Co.", domain: "riflepaperco.com" },
    { name: "Ban.do", domain: "bando.com" },
  ],

  finance: [
    { name: "Cash App", domain: "cash.app" },
    { name: "Robinhood", domain: "robinhood.com" },
    { name: "SoFi", domain: "sofi.com" },
    { name: "Chime", domain: "chime.com" },
    { name: "Wealthsimple", domain: "wealthsimple.com" },
    { name: "Acorns", domain: "acorns.com" },
    { name: "Betterment", domain: "betterment.com" },
    { name: "NerdWallet", domain: "nerdwallet.com" },
    { name: "Credit Karma", domain: "creditkarma.com" },
    { name: "Fundrise", domain: "fundrise.com" },
    { name: "Public.com", domain: "public.com" },
    { name: "Stash", domain: "stash.com" },
    { name: "Webull", domain: "webull.com" },
    { name: "M1 Finance", domain: "m1.com" },
    { name: "Wealthfront", domain: "wealthfront.com" },
    { name: "Ally Financial", domain: "ally.com" },
    { name: "Marcus by Goldman Sachs", domain: "marcus.com" },
    { name: "Discover", domain: "discover.com" },
    { name: "Capital One", domain: "capitalone.com" },
    { name: "American Express", domain: "americanexpress.com" },
    { name: "PayPal", domain: "paypal.com" },
    { name: "Venmo", domain: "venmo.com" },
    { name: "Klarna", domain: "klarna.com" },
    { name: "Afterpay", domain: "afterpay.com" },
    { name: "Wise", domain: "wise.com" },
  ],

  education: [
    { name: "MasterClass", domain: "masterclass.com" },
    { name: "Skillshare", domain: "skillshare.com" },
    { name: "Coursera", domain: "coursera.org" },
    { name: "Udemy", domain: "udemy.com" },
    { name: "LinkedIn Learning", domain: "linkedin.com/learning" },
    { name: "Duolingo", domain: "duolingo.com" },
    { name: "Babbel", domain: "babbel.com" },
    { name: "Khan Academy", domain: "khanacademy.org" },
    { name: "Brilliant", domain: "brilliant.org" },
    { name: "Codecademy", domain: "codecademy.com" },
    { name: "Teachable", domain: "teachable.com" },
    { name: "Thinkific", domain: "thinkific.com" },
    { name: "Kajabi", domain: "kajabi.com" },
    { name: "Wondrium", domain: "wondrium.com" },
    { name: "edX", domain: "edx.org" },
    { name: "Pluralsight", domain: "pluralsight.com" },
    { name: "DataCamp", domain: "datacamp.com" },
    { name: "Busuu", domain: "busuu.com" },
    { name: "CreativeLive", domain: "creativelive.com" },
    { name: "General Assembly", domain: "generalassemb.ly" },
    { name: "Springboard", domain: "springboard.com" },
    { name: "BrainPOP", domain: "brainpop.com" },
    { name: "Outschool", domain: "outschool.com" },
    { name: "ABCmouse", domain: "abcmouse.com" },
    { name: "Kumon", domain: "kumon.com" },
  ],

  entertainment: [
    { name: "Netflix", domain: "netflix.com" },
    { name: "Disney+", domain: "disneyplus.com" },
    { name: "Hulu", domain: "hulu.com" },
    { name: "HBO Max", domain: "max.com" },
    { name: "Paramount+", domain: "paramountplus.com" },
    { name: "Peacock", domain: "peacocktv.com" },
    { name: "Amazon Prime Video", domain: "primevideo.com" },
    { name: "Spotify", domain: "spotify.com" },
    { name: "Apple Music", domain: "music.apple.com" },
    { name: "YouTube Premium", domain: "youtube.com/premium" },
    { name: "Twitch", domain: "twitch.tv" },
    { name: "TikTok", domain: "tiktok.com" },
    { name: "Audible", domain: "audible.com" },
    { name: "Fandango", domain: "fandango.com" },
    { name: "AMC Theatres", domain: "amctheatres.com" },
    { name: "Live Nation", domain: "livenation.com" },
    { name: "Ticketmaster", domain: "ticketmaster.com" },
    { name: "Cameo", domain: "cameo.com" },
    { name: "Crunchyroll", domain: "crunchyroll.com" },
    { name: "Funimation", domain: "funimation.com" },
    { name: "Patreon", domain: "patreon.com" },
    { name: "Tubi", domain: "tubitv.com" },
    { name: "Roku", domain: "roku.com" },
    { name: "SiriusXM", domain: "siriusxm.com" },
    { name: "iHeartRadio", domain: "iheart.com" },
  ],

  sports: [
    { name: "Nike", domain: "nike.com" },
    { name: "Adidas", domain: "adidas.com" },
    { name: "Under Armour", domain: "underarmour.com" },
    { name: "New Balance", domain: "newbalance.com" },
    { name: "Puma", domain: "puma.com" },
    { name: "Fanatics", domain: "fanatics.com" },
    { name: "ESPN", domain: "espn.com" },
    { name: "DraftKings", domain: "draftkings.com" },
    { name: "FanDuel", domain: "fanduel.com" },
    { name: "Gatorade", domain: "gatorade.com" },
    { name: "Oakley", domain: "oakley.com" },
    { name: "Wilson", domain: "wilson.com" },
    { name: "Callaway Golf", domain: "callawaygolf.com" },
    { name: "TravisMathew", domain: "travismathew.com" },
    { name: "Topgolf", domain: "topgolf.com" },
    { name: "Titleist", domain: "titleist.com" },
    { name: "Rawlings", domain: "rawlings.com" },
    { name: "Easton", domain: "easton.com" },
    { name: "Mizuno", domain: "mizuno.com" },
    { name: "Asics", domain: "asics.com" },
    { name: "Brooks Running", domain: "brooksrunning.com" },
    { name: "Hoka", domain: "hoka.com" },
    { name: "On Running", domain: "on.com" },
    { name: "SeatGeek", domain: "seatgeek.com" },
    { name: "StockX", domain: "stockx.com" },
  ],

  music: [
    { name: "Spotify", domain: "spotify.com" },
    { name: "Apple Music", domain: "music.apple.com" },
    { name: "Tidal", domain: "tidal.com" },
    { name: "SoundCloud", domain: "soundcloud.com" },
    { name: "Bandcamp", domain: "bandcamp.com" },
    { name: "Fender", domain: "fender.com" },
    { name: "Gibson", domain: "gibson.com" },
    { name: "Roland", domain: "roland.com" },
    { name: "Yamaha", domain: "yamaha.com" },
    { name: "Native Instruments", domain: "native-instruments.com" },
    { name: "Ableton", domain: "ableton.com" },
    { name: "Splice", domain: "splice.com" },
    { name: "DistroKid", domain: "distrokid.com" },
    { name: "TuneCore", domain: "tunecore.com" },
    { name: "CD Baby", domain: "cdbaby.com" },
    { name: "Shure", domain: "shure.com" },
    { name: "Audio-Technica", domain: "audio-technica.com" },
    { name: "Sennheiser", domain: "sennheiser.com" },
    { name: "Focusrite", domain: "focusrite.com" },
    { name: "Universal Audio", domain: "uaudio.com" },
    { name: "iZotope", domain: "izotope.com" },
    { name: "Akai Professional", domain: "akaipro.com" },
    { name: "Pioneer DJ", domain: "pioneerdj.com" },
    { name: "Beatport", domain: "beatport.com" },
    { name: "Reverb", domain: "reverb.com" },
  ],

  health: [
    { name: "Hims & Hers", domain: "forhims.com" },
    { name: "Ro", domain: "ro.co" },
    { name: "Nurx", domain: "nurx.com" },
    { name: "Talkspace", domain: "talkspace.com" },
    { name: "BetterHelp", domain: "betterhelp.com" },
    { name: "Noom", domain: "noom.com" },
    { name: "WW (WeightWatchers)", domain: "weightwatchers.com" },
    { name: "Care/of", domain: "takecareof.com" },
    { name: "Ritual", domain: "ritual.com" },
    { name: "Seed", domain: "seed.com" },
    { name: "Athletic Greens", domain: "athleticgreens.com" },
    { name: "Oura Ring", domain: "ouraring.com" },
    { name: "Levels", domain: "levels.link" },
    { name: "InsideTracker", domain: "insidetracker.com" },
    { name: "Parsley Health", domain: "parsleyhealth.com" },
    { name: "Forward", domain: "goforward.com" },
    { name: "One Medical", domain: "onemedical.com" },
    { name: "Everlywell", domain: "everlywell.com" },
    { name: "23andMe", domain: "23andme.com" },
    { name: "Calm", domain: "calm.com" },
    { name: "Headspace", domain: "headspace.com" },
    { name: "Peloton", domain: "onepeloton.com" },
    { name: "Mindbody", domain: "mindbodyonline.com" },
    { name: "Vital Proteins", domain: "vitalproteins.com" },
    { name: "Moon Juice", domain: "moonjuice.com" },
  ],

  business: [
    { name: "Shopify", domain: "shopify.com" },
    { name: "Squarespace", domain: "squarespace.com" },
    { name: "Wix", domain: "wix.com" },
    { name: "HubSpot", domain: "hubspot.com" },
    { name: "Salesforce", domain: "salesforce.com" },
    { name: "Slack", domain: "slack.com" },
    { name: "Notion", domain: "notion.so" },
    { name: "Monday.com", domain: "monday.com" },
    { name: "Asana", domain: "asana.com" },
    { name: "Canva", domain: "canva.com" },
    { name: "QuickBooks", domain: "quickbooks.intuit.com" },
    { name: "FreshBooks", domain: "freshbooks.com" },
    { name: "Gusto", domain: "gusto.com" },
    { name: "Stripe", domain: "stripe.com" },
    { name: "Square", domain: "squareup.com" },
    { name: "Fiverr", domain: "fiverr.com" },
    { name: "Upwork", domain: "upwork.com" },
    { name: "Toptal", domain: "toptal.com" },
    { name: "WeWork", domain: "wework.com" },
    { name: "Calendly", domain: "calendly.com" },
    { name: "Zoom", domain: "zoom.us" },
    { name: "Grammarly", domain: "grammarly.com" },
    { name: "Loom", domain: "loom.com" },
    { name: "DocuSign", domain: "docusign.com" },
    { name: "Mailchimp", domain: "mailchimp.com" },
  ],

  parenting: [
    { name: "BabyList", domain: "babylist.com" },
    { name: "Lovevery", domain: "lovevery.com" },
    { name: "Hatch", domain: "hatchilab.com" },
    { name: "Nanit", domain: "nanit.com" },
    { name: "Owlet", domain: "owletcare.com" },
    { name: "Ergobaby", domain: "ergobaby.com" },
    { name: "UPPAbaby", domain: "uppababy.com" },
    { name: "Bugaboo", domain: "bugaboo.com" },
    { name: "Snoo", domain: "happiestbaby.com" },
    { name: "Babyganics", domain: "babyganics.com" },
    { name: "Honest Company", domain: "honest.com" },
    { name: "Hello Bello", domain: "hellobello.com" },
    { name: "Coterie", domain: "coterie.com" },
    { name: "Bobbie", domain: "hibobbie.com" },
    { name: "Ollie", domain: "ollieworld.com" },
    { name: "Kyte Baby", domain: "kytebaby.com" },
    { name: "Monica + Andy", domain: "monicaandandy.com" },
    { name: "Primary", domain: "primary.com" },
    { name: "Tea Collection", domain: "teacollection.com" },
    { name: "KiwiCo", domain: "kiwico.com" },
    { name: "Little Spoon", domain: "littlespoon.com" },
    { name: "Yumi", domain: "helloyumi.com" },
    { name: "Elvie", domain: "elvie.com" },
    { name: "Frida", domain: "frida.com" },
    { name: "Willow", domain: "willowpump.com" },
  ],

  pets: [
    { name: "Chewy", domain: "chewy.com" },
    { name: "BarkBox", domain: "barkbox.com" },
    { name: "Farmer's Dog", domain: "thefarmersdog.com" },
    { name: "Ollie Pets", domain: "myollie.com" },
    { name: "Nom Nom", domain: "nomnomnow.com" },
    { name: "PetSmart", domain: "petsmart.com" },
    { name: "Petco", domain: "petco.com" },
    { name: "Rover", domain: "rover.com" },
    { name: "Wag!", domain: "wagwalking.com" },
    { name: "Fi", domain: "tryfi.com" },
    { name: "Furbo", domain: "furbo.com" },
    { name: "Wild One", domain: "wildone.com" },
    { name: "Fable Pets", domain: "fablepets.com" },
    { name: "Open Farm", domain: "openfarmpet.com" },
    { name: "Wisdom Panel", domain: "wisdompanel.com" },
    { name: "Embark", domain: "embarkvet.com" },
    { name: "PupBox", domain: "pupbox.com" },
    { name: "Litter-Robot", domain: "litter-robot.com" },
    { name: "Catit", domain: "catit.com" },
    { name: "Kong", domain: "kongcompany.com" },
    { name: "Zesty Paws", domain: "zestypaws.com" },
    { name: "Native Pet", domain: "nativepet.com" },
    { name: "Sundays for Dogs", domain: "sundaysfordogs.com" },
    { name: "Jinx", domain: "jinx.com" },
    { name: "Pumpkin Pet Insurance", domain: "pumpkin.care" },
  ],

  automotive: [
    { name: "Tesla", domain: "tesla.com" },
    { name: "BMW", domain: "bmw.com" },
    { name: "Mercedes-Benz", domain: "mbusa.com" },
    { name: "Audi", domain: "audiusa.com" },
    { name: "Porsche", domain: "porsche.com" },
    { name: "Lexus", domain: "lexus.com" },
    { name: "Toyota", domain: "toyota.com" },
    { name: "Honda", domain: "honda.com" },
    { name: "Ford", domain: "ford.com" },
    { name: "Chevrolet", domain: "chevrolet.com" },
    { name: "Rivian", domain: "rivian.com" },
    { name: "Lucid Motors", domain: "lucidmotors.com" },
    { name: "Carvana", domain: "carvana.com" },
    { name: "Vroom", domain: "vroom.com" },
    { name: "AutoTrader", domain: "autotrader.com" },
    { name: "CarMax", domain: "carmax.com" },
    { name: "WeatherTech", domain: "weathertech.com" },
    { name: "Chemical Guys", domain: "chemicalguys.com" },
    { name: "Meguiar's", domain: "meguiars.com" },
    { name: "Turo", domain: "turo.com" },
    { name: "Hyundai", domain: "hyundaiusa.com" },
    { name: "Kia", domain: "kia.com" },
    { name: "Subaru", domain: "subaru.com" },
    { name: "Jeep", domain: "jeep.com" },
    { name: "Land Rover", domain: "landroverusa.com" },
  ],

  real_estate: [
    { name: "Zillow", domain: "zillow.com" },
    { name: "Redfin", domain: "redfin.com" },
    { name: "Realtor.com", domain: "realtor.com" },
    { name: "Trulia", domain: "trulia.com" },
    { name: "Compass", domain: "compass.com" },
    { name: "Opendoor", domain: "opendoor.com" },
    { name: "Offerpad", domain: "offerpad.com" },
    { name: "Rocket Mortgage", domain: "rocketmortgage.com" },
    { name: "Better.com", domain: "better.com" },
    { name: "LoanDepot", domain: "loandepot.com" },
    { name: "Fundrise", domain: "fundrise.com" },
    { name: "Roofstock", domain: "roofstock.com" },
    { name: "Arrived", domain: "arrivedhomes.com" },
    { name: "Divvy Homes", domain: "divvyhomes.com" },
    { name: "Flyhomes", domain: "flyhomes.com" },
    { name: "Homelight", domain: "homelight.com" },
    { name: "Clever Real Estate", domain: "listwithclever.com" },
    { name: "Apartments.com", domain: "apartments.com" },
    { name: "Rent.com", domain: "rent.com" },
    { name: "Zumper", domain: "zumper.com" },
    { name: "RentPath", domain: "rentpath.com" },
    { name: "CoStar", domain: "costar.com" },
    { name: "Matterport", domain: "matterport.com" },
    { name: "Hippo Insurance", domain: "hippo.com" },
    { name: "Lemonade", domain: "lemonade.com" },
  ],

  wedding: [
    { name: "The Knot", domain: "theknot.com" },
    { name: "Zola", domain: "zola.com" },
    { name: "WeddingWire", domain: "weddingwire.com" },
    { name: "David's Bridal", domain: "davidsbridal.com" },
    { name: "BHLDN", domain: "bhldn.com" },
    { name: "Azazie", domain: "azazie.com" },
    { name: "Grace Loves Lace", domain: "graceloveslace.com" },
    { name: "Lulus", domain: "lulus.com" },
    { name: "Birdy Grey", domain: "birdygrey.com" },
    { name: "Revelry", domain: "shoprevelry.com" },
    { name: "Minted", domain: "minted.com" },
    { name: "Shutterfly", domain: "shutterfly.com" },
    { name: "Papier", domain: "papier.com" },
    { name: "Joy", domain: "withjoy.com" },
    { name: "Riley & Grey", domain: "rileygrey.com" },
    { name: "Brilliant Earth", domain: "brilliantearth.com" },
    { name: "James Allen", domain: "jamesallen.com" },
    { name: "Blue Nile", domain: "bluenile.com" },
    { name: "Ring Concierge", domain: "ringconcierge.com" },
    { name: "Catbird", domain: "catbirdnyc.com" },
    { name: "Over the Moon", domain: "overthemoon.com" },
    { name: "Brides.com", domain: "brides.com" },
    { name: "Artifact Uprising", domain: "artifactuprising.com" },
    { name: "Honeyfund", domain: "honeyfund.com" },
    { name: "Miss to Mrs", domain: "misstomrsbox.com" },
  ],

  art_design: [
    { name: "Adobe", domain: "adobe.com" },
    { name: "Canva", domain: "canva.com" },
    { name: "Figma", domain: "figma.com" },
    { name: "Procreate", domain: "procreate.com" },
    { name: "Wacom", domain: "wacom.com" },
    { name: "Skillshare", domain: "skillshare.com" },
    { name: "Society6", domain: "society6.com" },
    { name: "Redbubble", domain: "redbubble.com" },
    { name: "Etsy", domain: "etsy.com" },
    { name: "Minted", domain: "minted.com" },
    { name: "Blick Art Materials", domain: "dickblick.com" },
    { name: "Jerry's Artarama", domain: "jerrysartarama.com" },
    { name: "Arteza", domain: "arteza.com" },
    { name: "Prismacolor", domain: "prismacolor.com" },
    { name: "Copic", domain: "copicmarker.com" },
    { name: "Cricut", domain: "cricut.com" },
    { name: "Silhouette", domain: "silhouetteamerica.com" },
    { name: "Spoonflower", domain: "spoonflower.com" },
    { name: "Creative Market", domain: "creativemarket.com" },
    { name: "Dribbble", domain: "dribbble.com" },
    { name: "Behance", domain: "behance.net" },
    { name: "99designs", domain: "99designs.com" },
    { name: "InVision", domain: "invisionapp.com" },
    { name: "Sketch", domain: "sketch.com" },
    { name: "Framer", domain: "framer.com" },
  ],

  photography: [
    { name: "Canon", domain: "usa.canon.com" },
    { name: "Nikon", domain: "nikon.com" },
    { name: "Sony Alpha", domain: "sony.com/electronics/interchangeable-lens-cameras" },
    { name: "Fujifilm", domain: "fujifilm-x.com" },
    { name: "GoPro", domain: "gopro.com" },
    { name: "DJI", domain: "dji.com" },
    { name: "Adobe Lightroom", domain: "lightroom.adobe.com" },
    { name: "Capture One", domain: "captureone.com" },
    { name: "Peak Design", domain: "peakdesign.com" },
    { name: "Moment", domain: "shopmoment.com" },
    { name: "SmugMug", domain: "smugmug.com" },
    { name: "Squarespace", domain: "squarespace.com" },
    { name: "Pixieset", domain: "pixieset.com" },
    { name: "ShootProof", domain: "shootproof.com" },
    { name: "Pic-Time", domain: "pic-time.com" },
    { name: "Sigma", domain: "sigmaphoto.com" },
    { name: "Tamron", domain: "tamron.com" },
    { name: "Profoto", domain: "profoto.com" },
    { name: "Godox", domain: "godox.com" },
    { name: "Manfrotto", domain: "manfrotto.com" },
    { name: "Lowepro", domain: "lowepro.com" },
    { name: "Think Tank Photo", domain: "thinktankphoto.com" },
    { name: "Shutterstock", domain: "shutterstock.com" },
    { name: "Getty Images", domain: "gettyimages.com" },
    { name: "500px", domain: "500px.com" },
  ],

  diy_home: [
    { name: "Home Depot", domain: "homedepot.com" },
    { name: "Lowe's", domain: "lowes.com" },
    { name: "Wayfair", domain: "wayfair.com" },
    { name: "IKEA", domain: "ikea.com" },
    { name: "Sherwin-Williams", domain: "sherwin-williams.com" },
    { name: "Benjamin Moore", domain: "benjaminmoore.com" },
    { name: "Behr Paint", domain: "behr.com" },
    { name: "Rust-Oleum", domain: "rustoleum.com" },
    { name: "DeWalt", domain: "dewalt.com" },
    { name: "Milwaukee Tool", domain: "milwaukeetool.com" },
    { name: "Ryobi", domain: "ryobitools.com" },
    { name: "Cricut", domain: "cricut.com" },
    { name: "Joann Fabrics", domain: "joann.com" },
    { name: "Michaels", domain: "michaels.com" },
    { name: "Hobby Lobby", domain: "hobbylobby.com" },
    { name: "Ace Hardware", domain: "acehardware.com" },
    { name: "Rejuvenation", domain: "rejuvenation.com" },
    { name: "Havenly", domain: "havenly.com" },
    { name: "Modsy", domain: "modsy.com" },
    { name: "Floor & Decor", domain: "flooranddecor.com" },
    { name: "Tile Bar", domain: "tilebar.com" },
    { name: "Build.com", domain: "build.com" },
    { name: "Overstock", domain: "overstock.com" },
    { name: "Ruggable", domain: "ruggable.com" },
    { name: "Joybird", domain: "joybird.com" },
  ],

  sustainability: [
    { name: "Patagonia", domain: "patagonia.com" },
    { name: "Allbirds", domain: "allbirds.com" },
    { name: "Tentree", domain: "tentree.com" },
    { name: "Girlfriend Collective", domain: "girlfriend.com" },
    { name: "Pact", domain: "wearpact.com" },
    { name: "Pela Case", domain: "pelacase.com" },
    { name: "Grove Collaborative", domain: "grove.co" },
    { name: "Blueland", domain: "blueland.com" },
    { name: "Bite Toothpaste", domain: "bitetoothpastebits.com" },
    { name: "Package Free Shop", domain: "packagefreeshop.com" },
    { name: "Who Gives A Crap", domain: "whogivesacrap.org" },
    { name: "Seventh Generation", domain: "seventhgeneration.com" },
    { name: "Dr. Bronner's", domain: "drbronner.com" },
    { name: "Reformation", domain: "thereformation.com" },
    { name: "Everlane", domain: "everlane.com" },
    { name: "ThredUp", domain: "thredup.com" },
    { name: "Poshmark", domain: "poshmark.com" },
    { name: "The RealReal", domain: "therealreal.com" },
    { name: "Stasher", domain: "stasherbag.com" },
    { name: "Hydro Flask", domain: "hydroflask.com" },
    { name: "S'well", domain: "swell.com" },
    { name: "Klean Kanteen", domain: "kleankanteen.com" },
    { name: "Bamford", domain: "bamford.com" },
    { name: "Avocado Mattress", domain: "avocadogreenmattress.com" },
    { name: "Coyuchi", domain: "coyuchi.com" },
  ],

  crypto_web3: [
    { name: "Coinbase", domain: "coinbase.com" },
    { name: "Binance", domain: "binance.com" },
    { name: "Kraken", domain: "kraken.com" },
    { name: "Gemini", domain: "gemini.com" },
    { name: "Crypto.com", domain: "crypto.com" },
    { name: "OpenSea", domain: "opensea.io" },
    { name: "MetaMask", domain: "metamask.io" },
    { name: "Ledger", domain: "ledger.com" },
    { name: "Trezor", domain: "trezor.io" },
    { name: "BlockFi", domain: "blockfi.com" },
    { name: "Uniswap", domain: "uniswap.org" },
    { name: "Aave", domain: "aave.com" },
    { name: "Solana", domain: "solana.com" },
    { name: "Polygon", domain: "polygon.technology" },
    { name: "Alchemy", domain: "alchemy.com" },
    { name: "Chainlink", domain: "chain.link" },
    { name: "Consensys", domain: "consensys.io" },
    { name: "Dapper Labs", domain: "dapperlabs.com" },
    { name: "Yuga Labs", domain: "yugalabs.io" },
    { name: "Immutable", domain: "immutable.com" },
    { name: "Phantom", domain: "phantom.app" },
    { name: "Rarible", domain: "rarible.com" },
    { name: "Foundation", domain: "foundation.app" },
    { name: "Rally", domain: "rally.io" },
    { name: "Axie Infinity", domain: "axieinfinity.com" },
  ],

  outdoor_adventure: [
    { name: "REI", domain: "rei.com" },
    { name: "The North Face", domain: "thenorthface.com" },
    { name: "Patagonia", domain: "patagonia.com" },
    { name: "Columbia Sportswear", domain: "columbia.com" },
    { name: "Arc'teryx", domain: "arcteryx.com" },
    { name: "Osprey Packs", domain: "osprey.com" },
    { name: "Yeti", domain: "yeti.com" },
    { name: "Hydro Flask", domain: "hydroflask.com" },
    { name: "Garmin", domain: "garmin.com" },
    { name: "AllTrails", domain: "alltrails.com" },
    { name: "Black Diamond", domain: "blackdiamondequipment.com" },
    { name: "Merrell", domain: "merrell.com" },
    { name: "Salomon", domain: "salomon.com" },
    { name: "Cotopaxi", domain: "cotopaxi.com" },
    { name: "prAna", domain: "prana.com" },
    { name: "Mountain Hardwear", domain: "mountainhardwear.com" },
    { name: "Big Agnes", domain: "bigagnes.com" },
    { name: "Sea to Summit", domain: "seatosummit.com" },
    { name: "Outdoor Voices", domain: "outdoorvoices.com" },
    { name: "Kelty", domain: "kelty.com" },
    { name: "Gregory Packs", domain: "gregorypacks.com" },
    { name: "MSR", domain: "msrgear.com" },
    { name: "Jetboil", domain: "jetboil.com" },
    { name: "Nemo Equipment", domain: "nemoequipment.com" },
    { name: "Rumpl", domain: "rumpl.com" },
  ],

  luxury: [
    { name: "Louis Vuitton", domain: "louisvuitton.com" },
    { name: "Gucci", domain: "gucci.com" },
    { name: "Chanel", domain: "chanel.com" },
    { name: "Dior", domain: "dior.com" },
    { name: "Prada", domain: "prada.com" },
    { name: "Hermès", domain: "hermes.com" },
    { name: "Balenciaga", domain: "balenciaga.com" },
    { name: "Versace", domain: "versace.com" },
    { name: "Burberry", domain: "burberry.com" },
    { name: "Fendi", domain: "fendi.com" },
    { name: "Saint Laurent", domain: "ysl.com" },
    { name: "Bottega Veneta", domain: "bottegaveneta.com" },
    { name: "Valentino", domain: "valentino.com" },
    { name: "Givenchy", domain: "givenchy.com" },
    { name: "Celine", domain: "celine.com" },
    { name: "Loewe", domain: "loewe.com" },
    { name: "Tom Ford", domain: "tomford.com" },
    { name: "Net-a-Porter", domain: "net-a-porter.com" },
    { name: "Farfetch", domain: "farfetch.com" },
    { name: "SSENSE", domain: "ssense.com" },
    { name: "Mytheresa", domain: "mytheresa.com" },
    { name: "Moncler", domain: "moncler.com" },
    { name: "Jimmy Choo", domain: "jimmychoo.com" },
    { name: "Cartier", domain: "cartier.com" },
    { name: "Tiffany & Co.", domain: "tiffany.com" },
  ],

  food_beverage: [
    { name: "Coca-Cola", domain: "coca-cola.com" },
    { name: "PepsiCo", domain: "pepsico.com" },
    { name: "Red Bull", domain: "redbull.com" },
    { name: "Monster Energy", domain: "monsterenergy.com" },
    { name: "Celsius", domain: "celsius.com" },
    { name: "Liquid Death", domain: "liquiddeath.com" },
    { name: "Olipop", domain: "drinkolipop.com" },
    { name: "Poppi", domain: "drinkpoppi.com" },
    { name: "Athletic Brewing", domain: "athleticbrewing.com" },
    { name: "Hint Water", domain: "drinkhint.com" },
    { name: "Bai", domain: "drinkbai.com" },
    { name: "Spindrift", domain: "drinkspindrift.com" },
    { name: "La Croix", domain: "lacroixwater.com" },
    { name: "Waterloo Sparkling Water", domain: "drinkwaterloo.com" },
    { name: "Vita Coco", domain: "vitacoco.com" },
    { name: "Oatly", domain: "oatly.com" },
    { name: "Califia Farms", domain: "califiafarms.com" },
    { name: "Chobani", domain: "chobani.com" },
    { name: "RXBAR", domain: "rxbar.com" },
    { name: "KIND", domain: "kindsnacks.com" },
    { name: "Clif Bar", domain: "clifbar.com" },
    { name: "Laird Superfood", domain: "lairdsuperfood.com" },
    { name: "Four Sigmatic", domain: "foursigmatic.com" },
    { name: "Mud/Wtr", domain: "mudwtr.com" },
    { name: "Graza", domain: "grfraza.co" },
  ],

  saas_tools: [
    { name: "HubSpot", domain: "hubspot.com" },
    { name: "Notion", domain: "notion.so" },
    { name: "Airtable", domain: "airtable.com" },
    { name: "Zapier", domain: "zapier.com" },
    { name: "Canva", domain: "canva.com" },
    { name: "Slack", domain: "slack.com" },
    { name: "Monday.com", domain: "monday.com" },
    { name: "ClickUp", domain: "clickup.com" },
    { name: "Asana", domain: "asana.com" },
    { name: "Trello", domain: "trello.com" },
    { name: "Miro", domain: "miro.com" },
    { name: "Loom", domain: "loom.com" },
    { name: "Calendly", domain: "calendly.com" },
    { name: "Typeform", domain: "typeform.com" },
    { name: "Webflow", domain: "webflow.com" },
    { name: "Vercel", domain: "vercel.com" },
    { name: "Supabase", domain: "supabase.com" },
    { name: "Stripe", domain: "stripe.com" },
    { name: "Intercom", domain: "intercom.com" },
    { name: "Zendesk", domain: "zendesk.com" },
    { name: "Datadog", domain: "datadoghq.com" },
    { name: "Twilio", domain: "twilio.com" },
    { name: "SendGrid", domain: "sendgrid.com" },
    { name: "Segment", domain: "segment.com" },
    { name: "Amplitude", domain: "amplitude.com" },
  ],

  dating_social: [
    { name: "Tinder", domain: "tinder.com" },
    { name: "Bumble", domain: "bumble.com" },
    { name: "Hinge", domain: "hinge.co" },
    { name: "Match.com", domain: "match.com" },
    { name: "OkCupid", domain: "okcupid.com" },
    { name: "Coffee Meets Bagel", domain: "coffeemeetsbagel.com" },
    { name: "The League", domain: "theleague.com" },
    { name: "Raya", domain: "rayatheapp.com" },
    { name: "Feeld", domain: "feeld.co" },
    { name: "Thursday", domain: "getthursday.com" },
    { name: "Snack", domain: "snack.dating" },
    { name: "Ship", domain: "getship.co" },
    { name: "Loveflutter", domain: "loveflutter.com" },
    { name: "Happn", domain: "happn.com" },
    { name: "Plenty of Fish", domain: "pof.com" },
    { name: "Zoosk", domain: "zoosk.com" },
    { name: "eHarmony", domain: "eharmony.com" },
    { name: "Facebook Dating", domain: "facebook.com/dating" },
    { name: "Discord", domain: "discord.com" },
    { name: "BeReal", domain: "bfrealapp.com" },
    { name: "Lemon8", domain: "lemon8-app.com" },
    { name: "Clubhouse", domain: "joinclubhouse.com" },
    { name: "Geneva", domain: "geneva.com" },
    { name: "IRL", domain: "irl.com" },
    { name: "Yubo", domain: "yubo.live" },
  ],

  kids_family: [
    { name: "Disney", domain: "disney.com" },
    { name: "LEGO", domain: "lego.com" },
    { name: "Mattel", domain: "mattel.com" },
    { name: "Hasbro", domain: "hasbro.com" },
    { name: "KiwiCo", domain: "kiwico.com" },
    { name: "Melissa & Doug", domain: "melissaanddoug.com" },
    { name: "Little Tikes", domain: "littletikes.com" },
    { name: "Fisher-Price", domain: "fisher-price.com" },
    { name: "VTech", domain: "vtechkids.com" },
    { name: "LeapFrog", domain: "leapfrog.com" },
    { name: "Primary", domain: "primary.com" },
    { name: "Hanna Andersson", domain: "hannaandersson.com" },
    { name: "Carter's", domain: "carters.com" },
    { name: "OshKosh B'Gosh", domain: "oshkosh.com" },
    { name: "Cat & Jack (Target)", domain: "target.com" },
    { name: "Nugget", domain: "nuggetcomfort.com" },
    { name: "Lovevery", domain: "lovevery.com" },
    { name: "Magna-Tiles", domain: "magnatiles.com" },
    { name: "Tonies", domain: "tonies.com" },
    { name: "Yoto", domain: "yotoplay.com" },
    { name: "Osmo", domain: "playosmo.com" },
    { name: "ABCmouse", domain: "abcmouse.com" },
    { name: "Outschool", domain: "outschool.com" },
    { name: "Little Passports", domain: "littlepassports.com" },
    { name: "Green Toys", domain: "greentoys.com" },
  ],

  legal_professional: [
    { name: "LegalZoom", domain: "legalzoom.com" },
    { name: "Rocket Lawyer", domain: "rocketlawyer.com" },
    { name: "Clio", domain: "clio.com" },
    { name: "LawPay", domain: "lawpay.com" },
    { name: "DocuSign", domain: "docusign.com" },
    { name: "PandaDoc", domain: "pandadoc.com" },
    { name: "HelloSign", domain: "hellosign.com" },
    { name: "Westlaw", domain: "westlaw.com" },
    { name: "LexisNexis", domain: "lexisnexis.com" },
    { name: "Avvo", domain: "avvo.com" },
    { name: "FindLaw", domain: "findlaw.com" },
    { name: "Justia", domain: "justia.com" },
    { name: "Nolo", domain: "nolo.com" },
    { name: "Lawyerist", domain: "lawyerist.com" },
    { name: "MyCase", domain: "mycase.com" },
    { name: "PracticePanther", domain: "practicepanther.com" },
    { name: "Smokeball", domain: "smokeball.com" },
    { name: "Filevine", domain: "filevine.com" },
    { name: "Relativity", domain: "relativity.com" },
    { name: "NetDocuments", domain: "netdocuments.com" },
    { name: "Litify", domain: "litify.com" },
    { name: "CASEpeer", domain: "casepeer.com" },
    { name: "Bill4Time", domain: "bill4time.com" },
    { name: "Zola Suite", domain: "zolasuite.com" },
    { name: "Assembly Neos", domain: "assemblysoftware.com" },
  ],

  nonprofit_cause: [
    { name: "GoFundMe", domain: "gofundme.com" },
    { name: "Change.org", domain: "change.org" },
    { name: "DonorsChoose", domain: "donorschoose.org" },
    { name: "Charity: Water", domain: "charitywater.org" },
    { name: "TOMS", domain: "toms.com" },
    { name: "Bombas", domain: "bombas.com" },
    { name: "Warby Parker", domain: "warbyparker.com" },
    { name: "Kiva", domain: "kiva.org" },
    { name: "Pencils of Promise", domain: "pencilsofpromise.org" },
    { name: "World Wildlife Fund", domain: "worldwildlife.org" },
    { name: "UNICEF", domain: "unicef.org" },
    { name: "St. Jude", domain: "stjude.org" },
    { name: "Make-A-Wish", domain: "wish.org" },
    { name: "Feeding America", domain: "feedingamerica.org" },
    { name: "Habitat for Humanity", domain: "habitat.org" },
    { name: "Red Cross", domain: "redcross.org" },
    { name: "Classy", domain: "classy.org" },
    { name: "Givebutter", domain: "givebutter.com" },
    { name: "Bloomerang", domain: "bloomerang.com" },
    { name: "Network for Good", domain: "networkforgood.com" },
    { name: "GlobalGiving", domain: "globalgiving.org" },
    { name: "Pledge", domain: "pledge.to" },
    { name: "Every Action", domain: "everyaction.com" },
    { name: "CauseVox", domain: "causevox.com" },
    { name: "Funraise", domain: "funraise.org" },
  ],

  skincare_derma: [
    { name: "CeraVe", domain: "cerave.com" },
    { name: "La Roche-Posay", domain: "laroche-posay.us" },
    { name: "The Ordinary", domain: "theordinary.com" },
    { name: "Drunk Elephant", domain: "drunkelephant.com" },
    { name: "Tatcha", domain: "tatcha.com" },
    { name: "SK-II", domain: "sk-ii.com" },
    { name: "Glow Recipe", domain: "glowrecipe.com" },
    { name: "Summer Fridays", domain: "summerfridays.com" },
    { name: "Supergoop", domain: "supergoop.com" },
    { name: "Paula's Choice", domain: "paulaschoice.com" },
    { name: "Kiehl's", domain: "kiehls.com" },
    { name: "Clinique", domain: "clinique.com" },
    { name: "Neutrogena", domain: "neutrogena.com" },
    { name: "Olay", domain: "olay.com" },
    { name: "Dr. Dennis Gross", domain: "drdennisgross.com" },
    { name: "Sunday Riley", domain: "sundayriley.com" },
    { name: "Youth to the People", domain: "youthtothepeople.com" },
    { name: "Herbivore Botanicals", domain: "herbivorebotanicals.com" },
    { name: "Biossance", domain: "biossance.com" },
    { name: "Versed", domain: "versedskin.com" },
    { name: "Cocokind", domain: "cocokind.com" },
    { name: "Good Molecules", domain: "goodmolecules.com" },
    { name: "Topicals", domain: "topicals.com" },
    { name: "Naturium", domain: "naturium.com" },
    { name: "Peach & Lily", domain: "peachandlily.com" },
  ],

  streetwear_urban: [
    { name: "Supreme", domain: "supremenewyork.com" },
    { name: "Off-White", domain: "off---white.com" },
    { name: "A Bathing Ape (BAPE)", domain: "bape.com" },
    { name: "Stussy", domain: "stussy.com" },
    { name: "Palace", domain: "palaceskateboards.com" },
    { name: "Kith", domain: "kith.com" },
    { name: "Fear of God", domain: "fearofgod.com" },
    { name: "ASSC (Anti Social Social Club)", domain: "antisocialsocialclub.com" },
    { name: "Essentials (FOG)", domain: "fearofgod.com" },
    { name: "New Era", domain: "neweracap.com" },
    { name: "Mitchell & Ness", domain: "mitchellandness.com" },
    { name: "StockX", domain: "stockx.com" },
    { name: "GOAT", domain: "goat.com" },
    { name: "Stadium Goods", domain: "stadiumgoods.com" },
    { name: "Bodega", domain: "bdgastore.com" },
    { name: "Undefeated", domain: "undefeated.com" },
    { name: "AIME Leon Dore", domain: "aimeleondore.com" },
    { name: "Rhude", domain: "rhude.com" },
    { name: "Ambush", domain: "ambushdesign.com" },
    { name: "Pleasures", domain: "pleasuresnow.com" },
    { name: "Brain Dead", domain: "wearebraindead.com" },
    { name: "Market (formerly Chinatown Market)", domain: "marketmarket.com" },
    { name: "The Hundreds", domain: "thehundreds.com" },
    { name: "10.Deep", domain: "10deep.com" },
    { name: "Billionaire Boys Club", domain: "bbcicecream.com" },
  ],

  mental_health: [
    { name: "BetterHelp", domain: "betterhelp.com" },
    { name: "Talkspace", domain: "talkspace.com" },
    { name: "Calm", domain: "calm.com" },
    { name: "Headspace", domain: "headspace.com" },
    { name: "Cerebral", domain: "cerebral.com" },
    { name: "Woebot", domain: "woebothealth.com" },
    { name: "Talkiatry", domain: "talkiatry.com" },
    { name: "Spring Health", domain: "springhealth.com" },
    { name: "Lyra Health", domain: "lyrahealth.com" },
    { name: "Ginger", domain: "ginger.com" },
    { name: "Modern Health", domain: "modernhealth.com" },
    { name: "Alma", domain: "helloalma.com" },
    { name: "Grew Wellness", domain: "grewwellness.com" },
    { name: "Real", domain: "joinreal.com" },
    { name: "Coa", domain: "joincoa.com" },
    { name: "Sanvello", domain: "sanvello.com" },
    { name: "Ten Percent Happier", domain: "tenpercent.com" },
    { name: "Insight Timer", domain: "insighttimer.com" },
    { name: "Shine", domain: "theshineapp.com" },
    { name: "Happify", domain: "happify.com" },
    { name: "Moodfit", domain: "getmoodfit.com" },
    { name: "Youper", domain: "youper.ai" },
    { name: "Aura", domain: "aurahealth.io" },
    { name: "MindShift", domain: "anxietycanada.com" },
    { name: "Nami", domain: "nami.org" },
  ],

  airlines_travel: [
    { name: "Delta Air Lines", domain: "delta.com" },
    { name: "United Airlines", domain: "united.com" },
    { name: "American Airlines", domain: "aa.com" },
    { name: "Southwest Airlines", domain: "southwest.com" },
    { name: "JetBlue", domain: "jetblue.com" },
    { name: "Alaska Airlines", domain: "alaskaair.com" },
    { name: "Spirit Airlines", domain: "spirit.com" },
    { name: "Frontier Airlines", domain: "flyfrontier.com" },
    { name: "Emirates", domain: "emirates.com" },
    { name: "Singapore Airlines", domain: "singaporeair.com" },
    { name: "British Airways", domain: "britishairways.com" },
    { name: "Lufthansa", domain: "lufthansa.com" },
    { name: "Air France", domain: "airfrance.com" },
    { name: "Qatar Airways", domain: "qatarairways.com" },
    { name: "Turkish Airlines", domain: "turkishairlines.com" },
    { name: "Cathay Pacific", domain: "cathaypacific.com" },
    { name: "Norwegian Air", domain: "norwegian.com" },
    { name: "Ryanair", domain: "ryanair.com" },
    { name: "EasyJet", domain: "easyjet.com" },
    { name: "Hawaiian Airlines", domain: "hawaiianairlines.com" },
    { name: "Breeze Airways", domain: "flybreeze.com" },
    { name: "CLEAR", domain: "clearme.com" },
    { name: "TSA PreCheck", domain: "tsa.gov/precheck" },
    { name: "Global Entry", domain: "ttp.cbp.dhs.gov" },
    { name: "LoungeBuddy", domain: "loungebuddy.com" },
  ],

  hospitality: [
    { name: "Marriott International", domain: "marriott.com" },
    { name: "Hilton", domain: "hilton.com" },
    { name: "Hyatt", domain: "hyatt.com" },
    { name: "IHG", domain: "ihg.com" },
    { name: "Wyndham", domain: "wyndhamhotels.com" },
    { name: "Accor", domain: "accor.com" },
    { name: "Four Seasons", domain: "fourseasons.com" },
    { name: "Ritz-Carlton", domain: "ritzcarlton.com" },
    { name: "W Hotels", domain: "whotels.com" },
    { name: "Ace Hotel", domain: "acehotel.com" },
    { name: "1 Hotels", domain: "1hotels.com" },
    { name: "Aman Resorts", domain: "aman.com" },
    { name: "Six Senses", domain: "sixsenses.com" },
    { name: "Soho House", domain: "sohohouse.com" },
    { name: "Graduate Hotels", domain: "graduatehotels.com" },
    { name: "citizenM", domain: "citizenm.com" },
    { name: "Moxy Hotels", domain: "moxy-hotels.marriott.com" },
    { name: "Sonder", domain: "sonder.com" },
    { name: "Mint House", domain: "minthouse.com" },
    { name: "Rosewood Hotels", domain: "rosewoodhotels.com" },
    { name: "Mandarin Oriental", domain: "mandarinoriental.com" },
    { name: "Peninsula Hotels", domain: "peninsula.com" },
    { name: "Banyan Tree", domain: "banyantree.com" },
    { name: "Nobu Hotels", domain: "nobuhotels.com" },
    { name: "Edition Hotels", domain: "editionhotels.com" },
  ],

  wine_spirits: [
    { name: "Drizly", domain: "drizly.com" },
    { name: "Winc", domain: "winc.com" },
    { name: "Bright Cellars", domain: "brightcellars.com" },
    { name: "Firstleaf", domain: "firstleaf.com" },
    { name: "Naked Wines", domain: "nakedwines.com" },
    { name: "Wine.com", domain: "wine.com" },
    { name: "Total Wine", domain: "totalwine.com" },
    { name: "Vivino", domain: "vivino.com" },
    { name: "Hendrick's Gin", domain: "hendricksgin.com" },
    { name: "Aviation Gin", domain: "aviationgin.com" },
    { name: "Casamigos", domain: "casamigos.com" },
    { name: "Patron", domain: "patrontequila.com" },
    { name: "Don Julio", domain: "donjulio.com" },
    { name: "Grey Goose", domain: "greygoose.com" },
    { name: "Tito's Vodka", domain: "titosvodka.com" },
    { name: "Maker's Mark", domain: "makersmark.com" },
    { name: "Bulleit Bourbon", domain: "bulleit.com" },
    { name: "Johnnie Walker", domain: "johnniewalker.com" },
    { name: "Moet & Chandon", domain: "moet.com" },
    { name: "Veuve Clicquot", domain: "veuveclicquot.com" },
    { name: "Athletic Brewing", domain: "athleticbrewing.com" },
    { name: "Haus", domain: "drink.haus" },
    { name: "De Soi", domain: "desoi.com" },
    { name: "Seedlip", domain: "seedlipdrinks.com" },
    { name: "Ghia", domain: "drinkghia.com" },
  ],

  cosmetics: [
    { name: "L'Oreal", domain: "loreal.com" },
    { name: "Estee Lauder", domain: "esteelauder.com" },
    { name: "Revlon", domain: "revlon.com" },
    { name: "Maybelline", domain: "maybelline.com" },
    { name: "CoverGirl", domain: "covergirl.com" },
    { name: "Bobbi Brown", domain: "bobbibrowncosmetics.com" },
    { name: "Smashbox", domain: "smashbox.com" },
    { name: "Bare Minerals", domain: "bareminerals.com" },
    { name: "IT Cosmetics", domain: "itcosmetics.com" },
    { name: "Lancôme", domain: "lancome-usa.com" },
    { name: "YSL Beauty", domain: "yslbeautyus.com" },
    { name: "Giorgio Armani Beauty", domain: "armanibeauty.com" },
    { name: "Clinique", domain: "clinique.com" },
    { name: "Glossier", domain: "glossier.com" },
    { name: "Rare Beauty", domain: "rarebeauty.com" },
    { name: "Haus Labs", domain: "hauslabs.com" },
    { name: "About Face", domain: "aboutface.com" },
    { name: "Rose Inc", domain: "roseinc.com" },
    { name: "Ami Cole", domain: "amicole.com" },
    { name: "Tower 28", domain: "tower28beauty.com" },
    { name: "Merit Beauty", domain: "meritbeauty.com" },
    { name: "Saie", domain: "saiehello.com" },
    { name: "Jones Road Beauty", domain: "jonesroadbeauty.com" },
    { name: "Danessa Myricks Beauty", domain: "danessamyricksbeauty.com" },
    { name: "KVD Vegan Beauty", domain: "kvdveganbeauty.com" },
  ],

  sporting_goods: [
    { name: "Dick's Sporting Goods", domain: "dickssportinggoods.com" },
    { name: "Academy Sports", domain: "academy.com" },
    { name: "Bass Pro Shops", domain: "basspro.com" },
    { name: "Cabela's", domain: "cabelas.com" },
    { name: "REI", domain: "rei.com" },
    { name: "Nike", domain: "nike.com" },
    { name: "Under Armour", domain: "underarmour.com" },
    { name: "The North Face", domain: "thenorthface.com" },
    { name: "Patagonia", domain: "patagonia.com" },
    { name: "Columbia", domain: "columbia.com" },
    { name: "Yeti", domain: "yeti.com" },
    { name: "Hydro Flask", domain: "hydroflask.com" },
    { name: "TaylorMade", domain: "taylormadegolf.com" },
    { name: "Callaway", domain: "callawaygolf.com" },
    { name: "Titleist", domain: "titleist.com" },
    { name: "Wilson", domain: "wilson.com" },
    { name: "Spalding", domain: "spalding.com" },
    { name: "Head", domain: "head.com" },
    { name: "Babolat", domain: "babolat.com" },
    { name: "Trek Bicycle", domain: "trekbikes.com" },
    { name: "Specialized", domain: "specialized.com" },
    { name: "Cannondale", domain: "cannondale.com" },
    { name: "Peloton", domain: "onepeloton.com" },
    { name: "Rogue Fitness", domain: "roguefitness.com" },
    { name: "Traeger Grills", domain: "traeger.com" },
  ],

  telecom: [
    { name: "Verizon", domain: "verizon.com" },
    { name: "AT&T", domain: "att.com" },
    { name: "T-Mobile", domain: "t-mobile.com" },
    { name: "Mint Mobile", domain: "mintmobile.com" },
    { name: "Visible", domain: "visible.com" },
    { name: "Google Fi", domain: "fi.google.com" },
    { name: "US Mobile", domain: "usmobile.com" },
    { name: "Boost Mobile", domain: "boostmobile.com" },
    { name: "Cricket Wireless", domain: "cricketwireless.com" },
    { name: "Metro by T-Mobile", domain: "metrobyt-mobile.com" },
    { name: "Comcast Xfinity", domain: "xfinity.com" },
    { name: "Spectrum", domain: "spectrum.com" },
    { name: "Cox Communications", domain: "cox.com" },
    { name: "Starlink", domain: "starlink.com" },
    { name: "HughesNet", domain: "hughesnet.com" },
    { name: "Ting", domain: "ting.com" },
    { name: "Republic Wireless", domain: "republicwireless.com" },
    { name: "Straight Talk", domain: "straighttalk.com" },
    { name: "Consumer Cellular", domain: "consumercellular.com" },
    { name: "Dish Network", domain: "dish.com" },
    { name: "RingCentral", domain: "ringcentral.com" },
    { name: "Vonage", domain: "vonage.com" },
    { name: "Ooma", domain: "ooma.com" },
    { name: "Twilio", domain: "twilio.com" },
    { name: "Bandwidth", domain: "bandwidth.com" },
  ],

  insurance: [
    { name: "Lemonade", domain: "lemonade.com" },
    { name: "Geico", domain: "geico.com" },
    { name: "Progressive", domain: "progressive.com" },
    { name: "State Farm", domain: "statefarm.com" },
    { name: "Allstate", domain: "allstate.com" },
    { name: "Liberty Mutual", domain: "libertymutual.com" },
    { name: "Nationwide", domain: "nationwide.com" },
    { name: "USAA", domain: "usaa.com" },
    { name: "Farmers Insurance", domain: "farmers.com" },
    { name: "Root Insurance", domain: "joinroot.com" },
    { name: "Hippo Insurance", domain: "hippo.com" },
    { name: "Metromile", domain: "metromile.com" },
    { name: "Bestow", domain: "bestow.com" },
    { name: "Haven Life", domain: "havenlife.com" },
    { name: "Ladder", domain: "ladderlife.com" },
    { name: "Ethos", domain: "ethoslife.com" },
    { name: "Oscar Health", domain: "hioscar.com" },
    { name: "Bright Health", domain: "brighthealthplan.com" },
    { name: "Clover Health", domain: "cloverhealth.com" },
    { name: "Pie Insurance", domain: "pieinsurance.com" },
    { name: "Next Insurance", domain: "nextinsurance.com" },
    { name: "Kin Insurance", domain: "kin.com" },
    { name: "Policygenius", domain: "policygenius.com" },
    { name: "The Zebra", domain: "thezebra.com" },
    { name: "Jerry", domain: "getjerry.com" },
  ],

  restaurants: [
    { name: "Chipotle", domain: "chipotle.com" },
    { name: "Chick-fil-A", domain: "chick-fil-a.com" },
    { name: "McDonald's", domain: "mcdonalds.com" },
    { name: "Starbucks", domain: "starbucks.com" },
    { name: "Dunkin'", domain: "dunkindonuts.com" },
    { name: "Wendy's", domain: "wendys.com" },
    { name: "Taco Bell", domain: "tacobell.com" },
    { name: "Domino's", domain: "dominos.com" },
    { name: "Sweetgreen", domain: "sweetgreen.com" },
    { name: "Cava", domain: "cava.com" },
    { name: "Shake Shack", domain: "shakeshack.com" },
    { name: "In-N-Out", domain: "in-n-out.com" },
    { name: "Panera Bread", domain: "panerabread.com" },
    { name: "Wingstop", domain: "wingstop.com" },
    { name: "Dutch Bros", domain: "dutchbros.com" },
    { name: "Raising Cane's", domain: "raisingcanes.com" },
    { name: "Five Guys", domain: "fiveguys.com" },
    { name: "Popeyes", domain: "popeyes.com" },
    { name: "Panda Express", domain: "pandaexpress.com" },
    { name: "Nando's", domain: "nandos.com" },
    { name: "Crumbl Cookies", domain: "crumblcookies.com" },
    { name: "Nothing Bundt Cakes", domain: "nothingbundtcakes.com" },
    { name: "MOD Pizza", domain: "modpizza.com" },
    { name: "Portillo's", domain: "portillos.com" },
    { name: "Boba Guys", domain: "bobaguys.com" },
  ],

  pharma_otc: [
    { name: "Johnson & Johnson", domain: "jnj.com" },
    { name: "Pfizer", domain: "pfizer.com" },
    { name: "Bayer", domain: "bayer.com" },
    { name: "GSK (GlaxoSmithKline)", domain: "gsk.com" },
    { name: "Reckitt (Mucinex/Delsym)", domain: "reckitt.com" },
    { name: "Procter & Gamble", domain: "pg.com" },
    { name: "Unilever", domain: "unilever.com" },
    { name: "Advil (Haleon)", domain: "advil.com" },
    { name: "Tylenol", domain: "tylenol.com" },
    { name: "Zyrtec", domain: "zyrtec.com" },
    { name: "Claritin", domain: "claritin.com" },
    { name: "Allegra", domain: "allegra.com" },
    { name: "Flonase", domain: "flonase.com" },
    { name: "Align Probiotics", domain: "alignprobiotics.com" },
    { name: "Culturelle", domain: "culturelle.com" },
    { name: "Nature Made", domain: "naturemade.com" },
    { name: "Nature's Bounty", domain: "naturesbounty.com" },
    { name: "Garden of Life", domain: "gardenoflife.com" },
    { name: "Olly", domain: "olly.com" },
    { name: "Liquid I.V.", domain: "liquid-iv.com" },
    { name: "Emergen-C", domain: "emergenc.com" },
    { name: "Hims & Hers", domain: "forhims.com" },
    { name: "Nurx", domain: "nurx.com" },
    { name: "Ro", domain: "ro.co" },
    { name: "GoodRx", domain: "goodrx.com" },
  ],

  elearning: [
    { name: "Coursera", domain: "coursera.org" },
    { name: "Udemy", domain: "udemy.com" },
    { name: "Skillshare", domain: "skillshare.com" },
    { name: "MasterClass", domain: "masterclass.com" },
    { name: "LinkedIn Learning", domain: "linkedin.com/learning" },
    { name: "Pluralsight", domain: "pluralsight.com" },
    { name: "DataCamp", domain: "datacamp.com" },
    { name: "Codecademy", domain: "codecademy.com" },
    { name: "Treehouse", domain: "teamtreehouse.com" },
    { name: "Brilliant", domain: "brilliant.org" },
    { name: "Khan Academy", domain: "khanacademy.org" },
    { name: "edX", domain: "edx.org" },
    { name: "Teachable", domain: "teachable.com" },
    { name: "Thinkific", domain: "thinkific.com" },
    { name: "Kajabi", domain: "kajabi.com" },
    { name: "Podia", domain: "podia.com" },
    { name: "Mighty Networks", domain: "mightynetworks.com" },
    { name: "Circle", domain: "circle.so" },
    { name: "Maven", domain: "maven.com" },
    { name: "Domestika", domain: "domestika.org" },
    { name: "FutureLearn", domain: "futurelearn.com" },
    { name: "Simplilearn", domain: "simplilearn.com" },
    { name: "Udacity", domain: "udacity.com" },
    { name: "CBT Nuggets", domain: "cbtnuggets.com" },
    { name: "A Cloud Guru", domain: "acloudguru.com" },
  ],

  clean_energy: [
    { name: "Tesla Energy", domain: "tesla.com/energy" },
    { name: "Sunrun", domain: "sunrun.com" },
    { name: "SunPower", domain: "sunpower.com" },
    { name: "Vivint Solar", domain: "vivintsolar.com" },
    { name: "Enphase Energy", domain: "enphase.com" },
    { name: "SolarEdge", domain: "solaredge.com" },
    { name: "ChargePoint", domain: "chargepoint.com" },
    { name: "EVgo", domain: "evgo.com" },
    { name: "Blink Charging", domain: "blinkcharging.com" },
    { name: "Rivian", domain: "rivian.com" },
    { name: "Lucid Motors", domain: "lucidmotors.com" },
    { name: "EcoFlow", domain: "ecoflow.com" },
    { name: "Jackery", domain: "jackery.com" },
    { name: "Goal Zero", domain: "goalzero.com" },
    { name: "Bluetti", domain: "bluettipower.com" },
    { name: "Span", domain: "span.io" },
    { name: "Sense", domain: "sense.com" },
    { name: "Arcadia", domain: "arcadia.com" },
    { name: "Community Solar", domain: "communitysolar.com" },
    { name: "Palmetto", domain: "palmetto.com" },
    { name: "Freedom Solar", domain: "freedomsolarpower.com" },
    { name: "Momentum Solar", domain: "momentumsolar.com" },
    { name: "Generac", domain: "generac.com" },
    { name: "Schneider Electric", domain: "se.com" },
    { name: "Siemens Energy", domain: "siemens-energy.com" },
  ],

  jewelry_watches: [
    { name: "Tiffany & Co.", domain: "tiffany.com" },
    { name: "Cartier", domain: "cartier.com" },
    { name: "Rolex", domain: "rolex.com" },
    { name: "Omega", domain: "omegawatches.com" },
    { name: "TAG Heuer", domain: "tagheuer.com" },
    { name: "Pandora", domain: "pandora.net" },
    { name: "Swarovski", domain: "swarovski.com" },
    { name: "David Yurman", domain: "davidyurman.com" },
    { name: "Mejuri", domain: "mejuri.com" },
    { name: "Kendra Scott", domain: "kendrascott.com" },
    { name: "BaubleBar", domain: "baublebar.com" },
    { name: "Gorjana", domain: "gorjana.com" },
    { name: "Ana Luisa", domain: "analuisa.com" },
    { name: "Brilliant Earth", domain: "brilliantearth.com" },
    { name: "James Allen", domain: "jamesallen.com" },
    { name: "Blue Nile", domain: "bluenile.com" },
    { name: "Ring Concierge", domain: "ringconcierge.com" },
    { name: "MVMT", domain: "mvmt.com" },
    { name: "Daniel Wellington", domain: "danielwellington.com" },
    { name: "Fossil", domain: "fossil.com" },
    { name: "Garmin", domain: "garmin.com" },
    { name: "Apple Watch", domain: "apple.com/watch" },
    { name: "Citizen", domain: "citizenwatch.com" },
    { name: "Aurate", domain: "auratenewyork.com" },
    { name: "Missoma", domain: "missoma.com" },
  ],

};
