// ─── Talent Plans ──────────────────────────────────────────────────
export const TALENT_PLANS = {
  free: {
    tier: 'free',
    name: 'Starter',
    monthly_price: 0,
    annual_price: 0,
    description: 'Explore the platform and taste the AI',
    features: [
      'Dashboard & profile',
      'Browse marketplace (view only)',
      '5 AI queries/month',
      'Up to 3 opportunities',
      'View deal details',
      'Basic approvals',
    ],
    limits: { ai_queries: 5, opportunities: 3, team_seats: 1, integrations: 0 },
  },
  rising: {
    tier: 'rising',
    name: 'Rising',
    monthly_price: 29,
    annual_price: 290,
    description: 'Full pipeline, outreach, and match engine',
    features: [
      'Everything in Starter plus:',
      'Full Deal Pipeline',
      'Match Engine & Contact Finder',
      'Outreach & Campaign Briefs',
      'Talent Discovery & Calendar',
      'Contract Templates',
      'Pitch Deck Builder & Deck Library',
      '50 AI queries/month',
      'AI Agents Hub (1 agent)',
    ],
    limits: { ai_queries: 50, opportunities: 999999, team_seats: 1, integrations: 0 },
  },
  pro: {
    tier: 'pro',
    name: 'Pro',
    monthly_price: 79,
    annual_price: 790,
    description: 'Analytics, intelligence, and advanced AI',
    features: [
      'Everything in Rising plus:',
      'Sequences & Warm Intro Network',
      'Deal Analytics & Comparison',
      'Market Intelligence & Spend Prediction',
      'ROI Simulator',
      'Data Rooms',
      'Event Management',
      'Full Analytics',
      'Unlimited AI queries',
      'AI Agents Hub (3 agents)',
    ],
    limits: { ai_queries: 999999, opportunities: 999999, team_seats: 1, integrations: 0 },
  },
  elite: {
    tier: 'elite',
    name: 'Elite',
    monthly_price: 199,
    annual_price: 1990,
    description: 'Teams, integrations, and enterprise scale',
    features: [
      'Everything in Pro plus:',
      'Teams (unlimited seats)',
      'Custom Reports',
      'Integrations & API access',
      'Data Import/Export',
      'Advanced AI Workflows',
      'Unlimited AI Agents',
      'Platform Overview',
      'Priority support',
    ],
    limits: { ai_queries: 999999, opportunities: 999999, team_seats: 999999, integrations: 999999 },
  },
};

// ─── Brand Plans ──────────────────────────────────────────────────
export const BRAND_PLANS = {
  free: {
    tier: 'free',
    name: 'Explorer',
    monthly_price: 0,
    annual_price: 0,
    description: 'Explore the platform and taste the AI',
    features: [
      'Dashboard & brand profile',
      'Browse marketplace (view only)',
      '5 AI queries/month',
      'Up to 3 opportunities',
      'View deal details',
      'Basic approvals',
    ],
    limits: { ai_queries: 5, opportunities: 3, team_seats: 1, integrations: 0 },
  },
  growth: {
    tier: 'growth',
    name: 'Growth',
    monthly_price: 49,
    annual_price: 490,
    description: 'Full pipeline, outreach, and match engine',
    features: [
      'Everything in Explorer plus:',
      'Full Deal Pipeline',
      'Match Engine & Contact Finder',
      'Outreach & Campaign Briefs',
      'Talent Discovery & Calendar',
      'Contract Templates',
      'Pitch Deck Builder & Deck Library',
      '50 AI queries/month',
      'AI Agents Hub (1 agent)',
    ],
    limits: { ai_queries: 50, opportunities: 999999, team_seats: 1, integrations: 0 },
  },
  scale: {
    tier: 'scale',
    name: 'Scale',
    monthly_price: 149,
    annual_price: 1490,
    description: 'Analytics, intelligence, and advanced AI',
    features: [
      'Everything in Growth plus:',
      'Sequences & Warm Intro Network',
      'Deal Analytics & Comparison',
      'Market Intelligence & Spend Prediction',
      'ROI Simulator',
      'Data Rooms',
      'Event Management',
      'Full Analytics',
      'Unlimited AI queries',
      'AI Agents Hub (3 agents)',
    ],
    limits: { ai_queries: 999999, opportunities: 999999, team_seats: 3, integrations: 0 },
  },
  enterprise: {
    tier: 'enterprise',
    name: 'Enterprise',
    monthly_price: 399,
    annual_price: 3990,
    description: 'Teams, integrations, and enterprise scale',
    features: [
      'Everything in Scale plus:',
      'Teams (unlimited seats)',
      'Custom Reports',
      'Integrations & API access',
      'Data Import/Export',
      'Advanced AI Workflows',
      'Unlimited AI Agents',
      'Platform Overview',
      'Dedicated success manager',
      'SSO & priority support',
    ],
    limits: { ai_queries: 999999, opportunities: 999999, team_seats: 999999, integrations: 999999 },
  },
};

// ─── Agency Plans ──────────────────────────────────────────────────
export const AGENCY_PLANS = {
  free: {
    tier: 'free',
    name: 'Explorer',
    monthly_price: 0,
    annual_price: 0,
    description: 'Explore the platform and taste the AI',
    features: [
      'Dashboard & agency profile',
      'Browse marketplace (view only)',
      '5 AI queries/month',
      'Up to 3 opportunities',
      'View deal details',
      'Basic approvals',
    ],
    limits: { ai_queries: 5, opportunities: 3, team_seats: 1, integrations: 0 },
  },
  starter: {
    tier: 'agency_starter',
    name: 'Agency Starter',
    monthly_price: 99,
    annual_price: 990,
    description: 'Full pipeline, outreach, and match engine',
    features: [
      'Everything in Explorer plus:',
      'Full Deal Pipeline',
      'Match Engine & Contact Finder',
      'Outreach & Campaign Briefs',
      'Talent Discovery & Calendar',
      'Contract Templates',
      'Pitch Deck Builder & Deck Library',
      '50 AI queries/month',
      'AI Agents Hub (1 agent)',
    ],
    limits: { ai_queries: 50, opportunities: 999999, team_seats: 3, integrations: 0 },
  },
  pro: {
    tier: 'agency_pro',
    name: 'Agency Pro',
    monthly_price: 249,
    annual_price: 2490,
    description: 'Analytics, intelligence, and advanced AI',
    features: [
      'Everything in Agency Starter plus:',
      'Sequences & Warm Intro Network',
      'Deal Analytics & Comparison',
      'Market Intelligence & Spend Prediction',
      'ROI Simulator',
      'Data Rooms',
      'Event Management',
      'Full Analytics',
      'Unlimited AI queries',
      'AI Agents Hub (3 agents)',
    ],
    limits: { ai_queries: 999999, opportunities: 999999, team_seats: 10, integrations: 3 },
  },
  enterprise: {
    tier: 'agency_enterprise',
    name: 'Agency Enterprise',
    monthly_price: 599,
    annual_price: 5990,
    description: 'Teams, integrations, and enterprise scale',
    features: [
      'Everything in Agency Pro plus:',
      'Teams (unlimited seats)',
      'Custom Reports',
      'Integrations & API access',
      'Data Import/Export',
      'Advanced AI Workflows',
      'Unlimited AI Agents',
      'Platform Overview',
      'Dedicated success manager',
      'White-label options',
      'SSO & priority support',
    ],
    limits: { ai_queries: 999999, opportunities: 999999, team_seats: 999999, integrations: 999999 },
  },
};

// ─── Manager Plans ──────────────────────────────────────────────────
export const MANAGER_PLANS = {
  free: {
    tier: 'free',
    name: 'Explorer',
    monthly_price: 0,
    annual_price: 0,
    description: 'Explore the platform and taste the AI',
    features: [
      'Dashboard & manager profile',
      'Browse marketplace (view only)',
      '5 AI queries/month',
      'Up to 3 opportunities',
      'View deal details',
      'Basic approvals',
    ],
    limits: { ai_queries: 5, opportunities: 3, team_seats: 1, integrations: 0 },
  },
  single: {
    tier: 'manager_single',
    name: 'Single Talent',
    monthly_price: 29,
    annual_price: 290,
    description: 'Full pipeline, outreach, and match engine',
    features: [
      'Everything in Explorer plus:',
      'Full Deal Pipeline',
      'Match Engine & Contact Finder',
      'Outreach & Campaign Briefs',
      'Talent Discovery & Calendar',
      'Contract Templates',
      'Pitch Deck Builder & Deck Library',
      '50 AI queries/month',
      'AI Agents Hub (1 agent)',
    ],
    limits: { ai_queries: 50, opportunities: 999999, team_seats: 1, integrations: 0 },
  },
  pro: {
    tier: 'manager_pro',
    name: 'Multi-Talent',
    monthly_price: 79,
    annual_price: 790,
    description: 'Analytics, intelligence, and advanced AI',
    features: [
      'Everything in Single Talent plus:',
      'Sequences & Warm Intro Network',
      'Deal Analytics & Comparison',
      'Market Intelligence & Spend Prediction',
      'ROI Simulator',
      'Data Rooms',
      'Event Management',
      'Full Analytics',
      'Unlimited AI queries',
      'AI Agents Hub (3 agents)',
    ],
    limits: { ai_queries: 999999, opportunities: 999999, team_seats: 3, integrations: 0 },
  },
  enterprise: {
    tier: 'manager_enterprise',
    name: 'Manager Enterprise',
    monthly_price: 199,
    annual_price: 1990,
    description: 'Teams, integrations, and enterprise scale',
    features: [
      'Everything in Multi-Talent plus:',
      'Teams (unlimited seats)',
      'Custom Reports',
      'Integrations & API access',
      'Data Import/Export',
      'Advanced AI Workflows',
      'Unlimited AI Agents',
      'Platform Overview',
      'Priority support',
    ],
    limits: { ai_queries: 999999, opportunities: 999999, team_seats: 999999, integrations: 999999 },
  },
};
