import { createClientFromRequest, corsHeaders } from '../_shared/supabase.ts';

// Complete Conference Master List (36 conferences)
const ALL_CONFERENCES = [
  { conference_name: "CES (Consumer Electronics Show)", industry_focus: "Technology", typical_date: "January (Jan 7-10, 2026)", location: "Las Vegas, NV", attendees: "200,000+", key_audience: "Tech executives, media, innovators", best_for_industries: "Tech, Consumer Electronics, Automotive, AI", sponsorship_range: "$50K-$500K+", why_attend: "Largest tech showcase; product launches; media coverage" },
  { conference_name: "NVIDIA GTC", industry_focus: "AI/Technology", typical_date: "March", location: "San Jose, CA", attendees: "20,000+ in-person", key_audience: "AI/ML professionals, developers", best_for_industries: "AI, Tech, Healthcare, Financial Services", sponsorship_range: "$25K-$200K", why_attend: "Premier AI conference; cutting-edge research" },
  { conference_name: "Google Cloud Next", industry_focus: "Cloud/Technology", typical_date: "April", location: "Las Vegas, NV", attendees: "30,000+", key_audience: "IT leaders, developers, enterprises", best_for_industries: "Cloud, AI, Tech, Enterprise", sponsorship_range: "$30K-$250K", why_attend: "Google ecosystem; cloud transformation" },
  { conference_name: "Microsoft Build", industry_focus: "Technology/Developer", typical_date: "May", location: "Seattle, WA", attendees: "6,000+ in-person", key_audience: "Developers, IT professionals", best_for_industries: "Tech, Software, AI, Enterprise", sponsorship_range: "$25K-$150K", why_attend: "Microsoft ecosystem; developer tools" },
  { conference_name: "Apple WWDC", industry_focus: "Technology", typical_date: "June", location: "Cupertino, CA (mostly virtual)", attendees: "Developers, media", key_audience: "Developers, media", best_for_industries: "Tech, Apps, Consumer Electronics", sponsorship_range: "By invitation", why_attend: "Apple ecosystem; iOS/Mac development" },
  { conference_name: "Google I/O", industry_focus: "Technology", typical_date: "May", location: "Mountain View, CA", attendees: "10,000+ in-person", key_audience: "Developers, AI researchers", best_for_industries: "Tech, AI, Cloud, Consumer Electronics", sponsorship_range: "$30K-$200K", why_attend: "Google's annual developer conference" },
  { conference_name: "SXSW", industry_focus: "Technology/Film/Music", typical_date: "March", location: "Austin, TX", attendees: "400,000+", key_audience: "Creatives, tech professionals, media", best_for_industries: "Tech, Entertainment, Automotive, Consumer", sponsorship_range: "$25K-$500K+", why_attend: "Cultural phenomenon; networking nexus" },
  { conference_name: "Money 20/20", industry_focus: "Financial Services", typical_date: "October", location: "Las Vegas, NV", attendees: "15,000+", key_audience: "Fintech leaders, investors", best_for_industries: "Finance, Banking, FinTech, Tech", sponsorship_range: "$50K-$500K", why_attend: "Largest financial services tech conference" },
  { conference_name: "Milken Global", industry_focus: "Finance/Investment", typical_date: "April-May", location: "Los Angeles, CA", attendees: "4,000+", key_audience: "Ultra-high-net-worth investors", best_for_industries: "Finance, Investment, Luxury", sponsorship_range: "$100K-$1M+", why_attend: "Elite networking; UHNW audience" },
  { conference_name: "SALT", industry_focus: "Finance/Investment", typical_date: "September", location: "Las Vegas, NV", attendees: "3,000+", key_audience: "Hedge fund managers, investors", best_for_industries: "Finance, Investment, Tech", sponsorship_range: "$50K-$500K", why_attend: "Premier alternative investment conference" },
  { conference_name: "Money 20/20", industry_focus: "Financial Services", typical_date: "October", location: "Las Vegas, NV", attendees: "15,000+", key_audience: "Fintech leaders, investors", best_for_industries: "Finance, Banking, FinTech, Tech", sponsorship_range: "$50K-$500K", why_attend: "Largest financial services tech conference" },
  { conference_name: "NRF Annual Convention", industry_focus: "Retail", typical_date: "January", location: "New York, NY", attendees: "35,000+", key_audience: "Retail executives, entrepreneurs", best_for_industries: "Retail, Tech, Logistics, Fashion", sponsorship_range: "$25K-$300K", why_attend: "Retail industry flagship event" },
  { conference_name: "ShopTalk", industry_focus: "Retail/E-Commerce", typical_date: "March", location: "Las Vegas, NV", attendees: "8,000+", key_audience: "Retail, e-commerce leaders", best_for_industries: "Retail, Tech, Consumer", sponsorship_range: "$30K-$250K", why_attend: "Modern retail transformation" },
  { conference_name: "IPPE (International Production and Processing Expo)", industry_focus: "Food & Agriculture", typical_date: "January", location: "Atlanta, GA", attendees: "30,000+", key_audience: "Food producers, processors", best_for_industries: "Food & Beverage, Agriculture, Retail", sponsorship_range: "$20K-$150K", why_attend: "Largest poultry/food processing show" },
  { conference_name: "NRA Conference (National Restaurant Association)", industry_focus: "Food Service", typical_date: "May", location: "Chicago, IL", attendees: "85,000+", key_audience: "Restaurant owners, operators", best_for_industries: "Food & Beverage, Tech, Hospitality", sponsorship_range: "$50K-$500K+", why_attend: "Restaurant industry's largest event" },
  { conference_name: "Summer Fancy Food Show", industry_focus: "Specialty Food", typical_date: "June", location: "New York, NY", attendees: "20,000+", key_audience: "Specialty food buyers, chefs", best_for_industries: "Food & Beverage, Retail, Hospitality", sponsorship_range: "$15K-$100K", why_attend: "Premium food product showcase" },
  { conference_name: "HIMSS (Healthcare Information and Management Systems Society)", industry_focus: "Healthcare Technology", typical_date: "March", location: "Orlando, FL", attendees: "45,000+", key_audience: "Healthcare IT professionals", best_for_industries: "Healthcare, Tech, Pharma", sponsorship_range: "$50K-$500K", why_attend: "Healthcare IT industry leader" },
  { conference_name: "J.P. Morgan Healthcare Conference", industry_focus: "Healthcare Investment", typical_date: "January", location: "San Francisco, CA", attendees: "4,000+", key_audience: "Healthcare investors, pharma execs", best_for_industries: "Healthcare, Pharma, Medical Devices", sponsorship_range: "$100K-$1M+", why_attend: "Premier healthcare investment event" },
  { conference_name: "IHRSA (International Health, Racquet & Sportsclub Association)", industry_focus: "Fitness/Sports", typical_date: "March", location: "San Diego, CA", attendees: "10,000+", key_audience: "Gym owners, fitness professionals", best_for_industries: "Sports & Fitness, Healthcare, Tech", sponsorship_range: "$25K-$200K", why_attend: "Fitness industry's largest conference" },
  { conference_name: "AICPA Engage", industry_focus: "Accounting", typical_date: "November", location: "Denver, CO", attendees: "8,000+", key_audience: "CPAs, accounting professionals", best_for_industries: "Accounting, Finance, Tech", sponsorship_range: "$20K-$150K", why_attend: "Professional accounting conference" },
  { conference_name: "BAI Beacon", industry_focus: "Banking", typical_date: "October", location: "New York, NY", attendees: "3,000+", key_audience: "Bank executives, leaders", best_for_industries: "Banking, Finance, Tech", sponsorship_range: "$50K-$250K", why_attend: "Banking strategy conference" },
  { conference_name: "ABA Annual Conference", industry_focus: "Banking", typical_date: "October", location: "Various", attendees: "5,000+", key_audience: "Bankers, financial professionals", best_for_industries: "Banking, Finance, Retail", sponsorship_range: "$25K-$200K", why_attend: "American Bankers Association flagship" },
  { conference_name: "Finovate", industry_focus: "Financial Innovation", typical_date: "May & September", location: "New York, San Francisco", attendees: "2,000+", key_audience: "FinTech startups, investors", best_for_industries: "FinTech, Finance, Tech", sponsorship_range: "$10K-$75K", why_attend: "FinTech innovation showcase" },
  { conference_name: "InsureTech Connect", industry_focus: "Insurance Technology", typical_date: "November", location: "Las Vegas, NV", attendees: "5,000+", key_audience: "Insurance execs, tech leaders", best_for_industries: "Insurance, Tech, Finance", sponsorship_range: "$30K-$200K", why_attend: "Insurance technology conference" },
  { conference_name: "RIMS (Risk and Insurance Management Society)", industry_focus: "Risk Management", typical_date: "April", location: "Various", attendees: "4,000+", key_audience: "Risk managers, insurance professionals", best_for_industries: "Insurance, Finance, Corporate", sponsorship_range: "$25K-$150K", why_attend: "Risk management professional association" },
  { conference_name: "NAIC (National Association of Insurance Commissioners)", industry_focus: "Insurance Regulation", typical_date: "December", location: "New Orleans, LA", attendees: "2,000+", key_audience: "Insurance regulators, commissioners", best_for_industries: "Insurance, Finance, Legal", sponsorship_range: "$15K-$100K", why_attend: "Insurance regulatory leadership" },
  { conference_name: "Detroit Auto Show", industry_focus: "Automotive", typical_date: "January", location: "Detroit, MI", attendees: "600,000+", key_audience: "Auto industry, consumers, media", best_for_industries: "Automotive, Tech, Consumer", sponsorship_range: "$100K-$5M+", why_attend: "North America's largest auto show" },
  { conference_name: "Delivering Alpha", industry_focus: "Investment/Finance", typical_date: "September", location: "New York, NY", attendees: "1,500+", key_audience: "Investment managers, hedge fund leads", best_for_industries: "Finance, Investment, Tech", sponsorship_range: "$75K-$500K", why_attend: "Elite investment conference" },
  { conference_name: "In|Vest", industry_focus: "Investment Management", typical_date: "June", location: "Austin, TX", attendees: "2,000+", key_audience: "Asset managers, investors", best_for_industries: "Finance, Investment, Tech", sponsorship_range: "$25K-$150K", why_attend: "Investment innovation summit" },
  { conference_name: "Art Basel", industry_focus: "Art/Luxury", typical_date: "December", location: "Miami Beach, FL", attendees: "75,000+", key_audience: "Art collectors, galleries, dealers", best_for_industries: "Luxury, Finance, Entertainment", sponsorship_range: "$50K-$500K+", why_attend: "Premier international art fair" },
  { conference_name: "VidCon", industry_focus: "Digital Video/Creator", typical_date: "July", location: "Anaheim, CA", attendees: "70,000+", key_audience: "Content creators, Gen Z/Millennials", best_for_industries: "Entertainment, Tech, Consumer", sponsorship_range: "$50K-$500K", why_attend: "Creator economy flagship event" }
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const created = await base44.asServiceRole.entities.Conference.bulkCreate(ALL_CONFERENCES);
    return new Response(JSON.stringify({ success: true, conferenceCount: created.length, message: `Imported ${created.length} conferences from Master List` }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});