/**
 * Agent configurations — routing tier, cache TTL, and system prompts for all 32 agents.
 */

export const TTL = {
  NONE: 0,
  SHORT: 5 * 60,        // 5 minutes
  MEDIUM: 60 * 60,      // 1 hour
  LONG: 6 * 60 * 60,    // 6 hours
  DAY: 24 * 60 * 60,    // 24 hours
};

export type RoutingTier = 'COMPLEX' | 'STANDARD' | 'REASONING' | 'FREE' | 'FAST' | 'BATCH';

export interface AgentConfig {
  name: string;
  tier: RoutingTier;
  systemPrompt?: string;
  maxTokens: number;
  temperature: number;
  useCache: boolean;
  useBatch: boolean;
  offPeakOnly: boolean;
  cacheTTL: number;
}

export const AGENTS: Record<string, AgentConfig> = {
  // === COMPLEX tier (Claude Sonnet) — deep reasoning, financial, strategic ===
  partnership_predictor: {
    name: 'Partnership Success Predictor',
    tier: 'COMPLEX',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  pricing_optimizer: {
    name: 'Optimal Pricing Recommender',
    tier: 'COMPLEX',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  contract_intelligence: {
    name: 'Contract Intelligence Analyzer',
    tier: 'COMPLEX',
    maxTokens: 4096,
    temperature: 0.2,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.LONG,
  },
  negotiation_coach: {
    name: 'Negotiation Coach',
    tier: 'COMPLEX',
    maxTokens: 4096,
    temperature: 0.4,
    useCache: false,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.NONE,
  },

  // === STANDARD tier (DeepSeek V3) — everyday tasks, summaries, analysis ===
  executive_briefing: {
    name: 'Executive Briefing Generator',
    tier: 'STANDARD',
    maxTokens: 8192,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  ai_command_center: {
    name: 'AI Command Center',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.5,
    useCache: false,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.NONE,
  },
  campaign_generator: {
    name: 'AI Campaign Generator',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.6,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  outreach_generator: {
    name: 'AI Outreach Generator',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.6,
    useCache: false,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.NONE,
  },
  creative_direction: {
    name: 'Creative Direction Generator',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.5,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  smart_alerts: {
    name: 'Smart Alert Generator',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  deal_patterns: {
    name: 'Deal Pattern Analyzer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  content_effectiveness: {
    name: 'Content Effectiveness Analyzer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  outreach_forecast: {
    name: 'Outreach Conversion Forecaster',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  success_factors: {
    name: 'Success Factor Identifier',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  post_mortem: {
    name: 'Campaign Post-Mortem Analyzer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  talent_trajectory: {
    name: 'Talent Value Trajectory Predictor',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  competitor_intel: {
    name: 'Competitor Intelligence Analyzer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  audience_overlap: {
    name: 'Audience Overlap Analyzer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  revenue_forecast: {
    name: 'Revenue Forecaster',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  relationship_health: {
    name: 'Relationship Health Monitor',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },
  brand_safety: {
    name: 'Brand Safety Analyzer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  trend_prediction: {
    name: 'Trend Prediction Engine',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.4,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  roster_optimization: {
    name: 'Roster Optimization Advisor',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  attribution: {
    name: 'Cross-Platform Attribution Modeler',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  compliance: {
    name: 'Compliance & Disclosure Analyzer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.2,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.LONG,
  },
  invoice_reconciliation: {
    name: 'Invoice Reconciliation Analyzer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.2,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  bulk_ops: {
    name: 'Bulk Agent Operations',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.4,
    useCache: false,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.NONE,
  },
  partnership_simulator: {
    name: 'Partnership Simulator',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.4,
    useCache: false,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.NONE,
  },
  deal_scorer: {
    name: 'Deal Leaderboard Scorer',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.SHORT,
  },

  // === FREE tier (Gemini Flash) — classification, tagging, translation ===
  agent_performance: {
    name: 'Agent Performance Analyzer',
    tier: 'FREE',
    maxTokens: 4096,
    temperature: 0.3,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.MEDIUM,
  },
  content_localizer: {
    name: 'Content Localizer',
    tier: 'FREE',
    maxTokens: 4096,
    temperature: 0.2,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.DAY,
  },
  data_extractor: {
    name: 'Data Extractor',
    tier: 'FREE',
    maxTokens: 4096,
    temperature: 0.1,
    useCache: true,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.DAY,
  },

  // === Catch-all for unknown agents ===
  default: {
    name: 'Default Agent',
    tier: 'STANDARD',
    maxTokens: 4096,
    temperature: 0.5,
    useCache: false,
    useBatch: false,
    offPeakOnly: false,
    cacheTTL: TTL.NONE,
  },
};

export function getAgent(name: string): AgentConfig {
  return AGENTS[name] || AGENTS.default;
}
