import { createClientFromRequest, corsHeaders } from '../_shared/supabase.ts';

const CULTURE_EVENTS = [
  {"event_name": "New Year's Day", "year": 2026, "month": "January", "dates": "Jan 1", "category": "Holiday/Civic", "subcategory": "Federal Holiday", "audience_reach": "National", "key_demographics": "All demographics", "best_industries": "Retail, Fitness, Health & Wellness, Financial Services, CPG", "location": "National", "tier": "1", "activation_opportunities": "Resolution campaigns, Q5 gift card redemption, fresh start messaging", "notes": "Resolution-focused; gift card peak redemption"},
  {"event_name": "CES (Consumer Electronics Show)", "year": 2026, "month": "January", "dates": "Jan 6-9", "category": "Conferences/Trade", "subcategory": "Tech Conference", "audience_reach": "200,000+ attendees", "key_demographics": "Tech industry, innovators, media", "best_industries": "Technology, Consumer Electronics, Automotive, AI/ML, Telecom, Media", "location": "Las Vegas, NV", "tier": "1", "activation_opportunities": "Innovation showcases, keynote sponsorships, demo spaces, press events", "notes": "World's largest tech event"},
  {"event_name": "NFL Wild Card Weekend", "year": 2026, "month": "January", "dates": "Jan 10-12", "category": "Sports", "subcategory": "NFL", "audience_reach": "30M+ per game", "key_demographics": "Mass market, 70% male, HHI $75K+", "best_industries": "Beer/Alcohol, Automotive, Insurance, QSR, Snacks, Wireless", "location": "Various", "tier": "1", "activation_opportunities": "Gameday promotions, sports bars, fantasy playoffs", "notes": "Playoff intensity begins"},
  {"event_name": "Golden Globe Awards", "year": 2026, "month": "January", "dates": "Jan 11", "category": "Entertainment", "subcategory": "Awards Show", "audience_reach": "9.3M viewers", "key_demographics": "Adults 25-54, entertainment enthusiasts", "best_industries": "Luxury, Beauty, Fashion, Spirits, Automotive, Streaming", "location": "Los Angeles, CA", "tier": "2", "activation_opportunities": "Red carpet partnerships, viewing parties, celebrity activations", "notes": "Hollywood's party of the year"},
  {"event_name": "NFL Divisional Round", "year": 2026, "month": "January", "dates": "Jan 17-18", "category": "Sports", "subcategory": "NFL", "audience_reach": "35M+ per game", "key_demographics": "Mass market, 70% male", "best_industries": "Beer/Alcohol, Automotive, QSR, Sports Betting", "location": "Various", "tier": "1", "activation_opportunities": "Regional activations, hometown hero campaigns", "notes": "High-stakes playoff weekend"},
  {"event_name": "Super Bowl LX", "year": 2026, "month": "February", "dates": "Feb 8", "category": "Sports", "subcategory": "NFL", "audience_reach": "127M+ US", "key_demographics": "Mass market, 70% male", "best_industries": "Beer/Alcohol, Automotive, Insurance, QSR, Tech, Retail", "location": "Santa Clara, CA", "tier": "1", "activation_opportunities": "TV spots, halftime activations, experiential marketing, hospitality events", "notes": "Most-watched sporting event; Bad Bunny halftime"},
  {"event_name": "Winter Olympics 2026", "year": 2026, "month": "February", "dates": "Feb 6-22", "category": "Sports", "subcategory": "Winter Olympics", "audience_reach": "30-40M US viewers", "key_demographics": "All demographics, families", "best_industries": "All industries - cross-category appeal", "location": "Milan-Cortina, Italy", "tier": "1", "activation_opportunities": "NBC broadcast sponsorships, athlete partnerships, Olympic heritage campaigns", "notes": "Global prestige event; 1B+ worldwide"},
  {"event_name": "NBA All-Star Weekend", "year": 2026, "month": "February", "dates": "Feb 15-17", "category": "Sports", "subcategory": "NBA", "audience_reach": "15M+ US viewers", "key_demographics": "Urban, 35% female, multicultural", "best_industries": "Tech, Apparel, Automotive, Spirits, Entertainment", "location": "New Orleans, LA", "tier": "2", "activation_opportunities": "Celebrity partnerships, fashion events, tech showcases", "notes": "Entertainment meets sports"},
  {"event_name": "NCAA Tournament (March Madness)", "year": 2026, "month": "March", "dates": "Mar 17-Apr 6", "category": "Sports", "subcategory": "College Basketball", "audience_reach": "18M+ final four viewers", "key_demographics": "Office workers, alumni, 40-65 skew", "best_industries": "QSR, Beer, Insurance, Betting, Office Supply", "location": "Various", "tier": "1", "activation_opportunities": "Office bracket campaigns, watch party sponsorships, regional activations", "notes": "Highest engagement in workplace"},
  {"event_name": "Academy Awards (Oscars)", "year": 2026, "month": "March", "dates": "Mar 15", "category": "Entertainment", "subcategory": "Awards Show", "audience_reach": "11.5M US viewers", "key_demographics": "Adults 25-54, entertainment industry", "best_industries": "Luxury, Fashion, Beauty, Automotive, Streaming", "location": "Los Angeles, CA", "tier": "1", "activation_opportunities": "Red carpet partnerships, luxury brand activations, fashion events", "notes": "Highest prestige awards ceremony"},
  {"event_name": "Coachella Music Festival", "year": 2026, "month": "April", "dates": "Apr 10-19", "category": "Entertainment", "subcategory": "Music Festival", "audience_reach": "250,000+ attendees", "key_demographics": "Gen Z, Millennials, 60% female", "best_industries": "Fashion, Beauty, Tech, Spirits, Apparel", "location": "Indio, CA", "tier": "2", "activation_opportunities": "Brand activations, influencer partnerships, social media content", "notes": "Culture-defining music festival; influencer magnet"},
  {"event_name": "Masters Golf Tournament", "year": 2026, "month": "April", "dates": "Apr 9-12", "category": "Sports", "subcategory": "Golf", "audience_reach": "3M+ viewers, 100M+ reach", "key_demographics": "Male-skewed, affluent, 45-65", "best_industries": "Automotive, Luxury, Financial Services, Spirits", "location": "Augusta, GA", "tier": "1", "activation_opportunities": "Hospitality, luxury partnerships, prestige branding", "notes": "Most exclusive golf event; high-net-worth audience"},
  {"event_name": "Easter", "year": 2026, "month": "April", "dates": "Apr 5", "category": "Holiday/Civic", "subcategory": "Religious Holiday", "audience_reach": "National", "key_demographics": "All demographics, families", "best_industries": "Retail, Fashion, Apparel, CPG, Candy, Travel", "location": "National", "tier": "1", "activation_opportunities": "Family campaigns, spring collection launches, gift bundles", "notes": "2nd largest consumer spending holiday"},
  {"event_name": "Kentucky Derby", "year": 2026, "month": "May", "dates": "May 2", "category": "Sports", "subcategory": "Horse Racing", "audience_reach": "20M+ viewers, 150K attendees", "key_demographics": "Affluent, 50-70, male-skewed", "best_industries": "Spirits, Automotive, Luxury, Fashion, Financial Services", "location": "Louisville, KY", "tier": "1", "activation_opportunities": "Hospitality, fashion partnerships, mint julep sponsorships", "notes": "Most prestigious horse race; haute couture event"},
  {"event_name": "Memorial Day", "year": 2026, "month": "May", "dates": "May 25", "category": "Holiday/Civic", "subcategory": "Federal Holiday", "audience_reach": "National", "key_demographics": "All demographics, families", "best_industries": "Retail, Automotive, Travel, Home & Garden, Spirits", "location": "National", "tier": "1", "activation_opportunities": "Sales events, travel promotions, patriotic campaigns", "notes": "Unofficial summer kickoff; #2 consumer spending day"},
  {"event_name": "NBA Finals", "year": 2026, "month": "June", "dates": "Jun 4-18", "category": "Sports", "subcategory": "NBA", "audience_reach": "12M+ US viewers", "key_demographics": "Urban, multicultural, 35% female", "best_industries": "Tech, Apparel, Automotive, Spirits, Entertainment", "location": "Various", "tier": "1", "activation_opportunities": "Broadcast sponsorships, arena activations, celebrity partnerships", "notes": "Annual championship; global reach"},
  {"event_name": "Father's Day", "year": 2026, "month": "June", "dates": "Jun 21", "category": "Holiday/Civic", "subcategory": "Consumer Holiday", "audience_reach": "National", "key_demographics": "All demographics, male-skewed", "best_industries": "Retail, Tech, Automotive, Spirits, Apparel, Sports", "location": "National", "tier": "1", "activation_opportunities": "Gift guides, male-focused campaigns, sports partnerships", "notes": "Major retail driver; golf/sports overlap"},
  {"event_name": "FIFA World Cup 2026", "year": 2026, "month": "June", "dates": "Jun 11-Jul 19", "category": "Sports", "subcategory": "International Soccer", "audience_reach": "6B+ global, 50M+ US", "key_demographics": "Global, 76% under 45, Hispanic-dominant in US", "best_industries": "All industries - global megaevent", "location": "USA, Mexico, Canada (Multi-nation)", "tier": "1", "activation_opportunities": "Broadcast rights, stadium sponsorships, team partnerships, fan activation", "notes": "First tri-nation World Cup; US hosts; massive Hispanic opportunity"},
  {"event_name": "Independence Day", "year": 2026, "month": "July", "dates": "Jul 4", "category": "Holiday/Civic", "subcategory": "Federal Holiday", "audience_reach": "National", "key_demographics": "All demographics, families", "best_industries": "Beer/Alcohol, Spirits, Automotive, Retail, Travel, Food", "location": "National", "tier": "1", "activation_opportunities": "Patriotic campaigns, barbecue tie-ins, travel promotions", "notes": "#1 beer consumption day; high spirits/alcohol spend"},
  {"event_name": "MLB All-Star Game", "year": 2026, "month": "July", "dates": "Jul 14", "category": "Sports", "subcategory": "MLB", "audience_reach": "8M+ viewers", "key_demographics": "Families, 45-65 skew", "best_industries": "Beer, Insurance, Automotive, Sports", "location": "New York, NY", "tier": "2", "activation_opportunities": "Fan experiences, Home Run Derby sponsorships, ballpark activations", "notes": "Mid-season entertainment"},
  {"event_name": "US Open Tennis", "year": 2026, "month": "August", "dates": "Aug 24-Sep 13", "category": "Sports", "subcategory": "Tennis", "audience_reach": "3M+ viewers, affluent", "key_demographics": "Affluent, educated, 45-70, female-skewed", "best_industries": "Luxury, Automotive, Financial Services, Fashion, Spirits", "location": "New York, NY", "tier": "2", "activation_opportunities": "VIP hospitality, luxury partnerships, fashion events", "notes": "Prestige tennis event; NYC glamour factor"},
  {"event_name": "Back to School", "year": 2026, "month": "August", "dates": "Aug 1-31", "category": "Holiday/Civic", "subcategory": "Consumer Shopping", "audience_reach": "National", "key_demographics": "Parents, students, 25-45", "best_industries": "Retail, Tech, Apparel, Office Supply, Beauty, Wireless", "location": "National", "tier": "1", "activation_opportunities": "School supply campaigns, tech launches, fashion collections", "notes": "2nd largest retail event after Christmas"},
  {"event_name": "Labor Day", "year": 2026, "month": "September", "dates": "Sep 7", "category": "Holiday/Civic", "subcategory": "Federal Holiday", "audience_reach": "National", "key_demographics": "All demographics, families", "best_industries": "Retail, Automotive, Travel, Apparel, Home & Garden", "location": "National", "tier": "1", "activation_opportunities": "Summer clearance, fall collection launches, travel promotions", "notes": "End of summer; back to routine messaging"},
  {"event_name": "NFL Season Opener", "year": 2026, "month": "September", "dates": "Sep 10", "category": "Sports", "subcategory": "NFL", "audience_reach": "30M+ viewers", "key_demographics": "Mass market, 70% male, HHI $75K+", "best_industries": "Beer, Automotive, Insurance, QSR, Wireless, Sports Betting", "location": "Various", "tier": "1", "activation_opportunities": "Team partnerships, bar activations, fantasy tie-ins", "notes": "Start of peak sports season"},
  {"event_name": "US Open Golf Championship", "year": 2026, "month": "June", "dates": "Jun 15-21", "category": "Sports", "subcategory": "Golf", "audience_reach": "3M+ viewers, affluent", "key_demographics": "Affluent, educated, 50-70, male-skewed", "best_industries": "Automotive, Luxury, Financial Services, Spirits, Watches", "location": "Various", "tier": "1", "activation_opportunities": "Sponsorships, luxury hospitality, prestige branding", "notes": "Second-most prestigious golf tournament"},
  {"event_name": "Hispanic Heritage Month", "year": 2026, "month": "September", "dates": "Sep 15-Oct 15", "category": "Awareness Month", "subcategory": "Cultural Celebration", "audience_reach": "65M+ Hispanic Americans", "key_demographics": "Hispanic/Latino 18-65, bilingual", "best_industries": "All industries - major segment", "location": "National", "tier": "1", "activation_opportunities": "Bilingual campaigns, cultural events, community sponsorships, family-focused messaging", "notes": "Largest minority segment ($2.8T buying power); CRITICAL for Hispanic brands"},
  {"event_name": "Thanksgiving", "year": 2026, "month": "November", "dates": "Nov 26", "category": "Holiday/Civic", "subcategory": "Family Holiday", "audience_reach": "National", "key_demographics": "All demographics, families", "best_industries": "Retail, Food, Travel, Spirits, Automotive, CPG", "location": "National", "tier": "1", "activation_opportunities": "Family campaigns, food/beverage tie-ins, travel promotions, gratitude messaging", "notes": "2nd largest travel day; family-centric"},
  {"event_name": "Black Friday", "year": 2026, "month": "November", "dates": "Nov 27", "category": "Holiday/Civic", "subcategory": "Shopping Event", "audience_reach": "National", "key_demographics": "All demographics, deal-seekers", "best_industries": "Retail, Tech, Apparel, Home & Garden, Automotive", "location": "National", "tier": "1", "activation_opportunities": "Major sales campaigns, flash deals, door busters, online promotions", "notes": "Largest retail day; kicks off holiday season"},
  {"event_name": "Cyber Monday", "year": 2026, "month": "December", "dates": "Dec 1", "category": "Holiday/Civic", "subcategory": "Shopping Event", "audience_reach": "National", "key_demographics": "All demographics, online-first", "best_industries": "Retail, Tech, Apparel, Electronics, Streaming", "location": "National", "tier": "1", "activation_opportunities": "Online-exclusive deals, digital campaigns, app promotions", "notes": "Peak online shopping day"},
  {"event_name": "Christmas", "year": 2026, "month": "December", "dates": "Dec 25", "category": "Holiday/Civic", "subcategory": "Religious Holiday", "audience_reach": "National", "key_demographics": "All demographics, families", "best_industries": "Retail, Spirits, Travel, Entertainment, Tech, Luxury", "location": "National", "tier": "1", "activation_opportunities": "Holiday campaigns, gift guides, family messaging, charitable tie-ins", "notes": "#1 consumer spending holiday; nostalgia/family-focused"},
  {"event_name": "MLB Playoff Wildcard", "year": 2026, "month": "October", "dates": "Oct 6-7", "category": "Sports", "subcategory": "MLB", "audience_reach": "8M+ viewers", "key_demographics": "Sports fans, 40-65", "best_industries": "Beer, Automotive, Insurance, Sports", "location": "Various", "tier": "2", "activation_opportunities": "Regional activations, hometown campaigns, bar sponsorships", "notes": "Playoff intensity begins"},
  {"event_name": "Halloween", "year": 2026, "month": "October", "dates": "Oct 31", "category": "Holiday/Civic", "subcategory": "Consumer Holiday", "audience_reach": "National", "key_demographics": "Families, Gen X/Millennials, 25-54", "best_industries": "Retail, Candy, Costumes, Home Decor, Spirits, Entertainment", "location": "National", "tier": "1", "activation_opportunities": "Costume contests, Halloween parties, seasonal collections, spooky campaigns", "notes": "Highest Halloween spending among Millennials ($447)"}
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return new Response(JSON.stringify({ error: 'Forbidden: Admin access required' }), { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const result = await base44.asServiceRole.entities.CultureEvent.bulkCreate(CULTURE_EVENTS);
    return new Response(JSON.stringify({ success: true, created: result.length, message: `Imported ${result.length} culture events` }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});