/**
 * pages.config.js - Page routing configuration with lazy loading
 * All pages use React.lazy() for code splitting — each page loads on demand.
 */
import { lazy } from 'react';
import __Layout from './Layout.jsx';

const PAGES = {
    "AdminDashboard": lazy(() => import('./pages/AdminDashboard')),
    "AdminDataManager": lazy(() => import('./pages/AdminDataManager')),
    "AIAgentsHub": lazy(() => import('./pages/AIAgentsHub')),
    "AIAnalytics": lazy(() => import('./pages/AIAnalytics')),
    "AICommandCenter": lazy(() => import('./pages/AICommandCenter')),
    "AIFeatures": lazy(() => import('./pages/AIFeatures')),
    "Analytics": lazy(() => import('./pages/Analytics')),
    "Approvals": lazy(() => import('./pages/Approvals')),
    "BillingHistory": lazy(() => import('./pages/BillingHistory')),
    "BrandDashboard": lazy(() => import('./pages/BrandDashboard')),
    "Brands": lazy(() => import('./pages/Brands')),
    "CampaignBriefGenerator": lazy(() => import('./pages/CampaignBriefGenerator')),
    "ConnectAccounts": lazy(() => import('./pages/ConnectAccounts')),
    "ContactFinder": lazy(() => import('./pages/ContactFinder')),
    "CreateOpportunity": lazy(() => import('./pages/CreateOpportunity')),
    "CultureCalendar": lazy(() => import('./pages/CultureCalendar')),
    "CustomReports": lazy(() => import('./pages/CustomReports')),
    "Dashboard": lazy(() => import('./pages/Dashboard')),
    "DataImportExport": lazy(() => import('./pages/DataImportExport')),
    "DealAnalytics": lazy(() => import('./pages/DealAnalytics')),
    "DealDetail": lazy(() => import('./pages/DealDetail')),
    "DealScoreLeaderboard": lazy(() => import('./pages/DealScoreLeaderboard')),
    "DemographicTargeting": lazy(() => import('./pages/DemographicTargeting')),
    "EventManagement": lazy(() => import('./pages/EventManagement')),
    "IndustryEvents": lazy(() => import('./pages/IndustryEvents')),
    "Integrations": lazy(() => import('./pages/Integrations')),
    "MarketIntelligence": lazy(() => import('./pages/MarketIntelligence')),
    "Marketplace": lazy(() => import('./pages/Marketplace')),
    "MasterCalendar": lazy(() => import('./pages/MasterCalendar')),
    "MatchEngine": lazy(() => import('./pages/MatchEngine')),
    "Notifications": lazy(() => import('./pages/Notifications')),
    "Onboarding": lazy(() => import('./pages/Onboarding')),
    "Outreach": lazy(() => import('./pages/Outreach')),
    "Partnerships": lazy(() => import('./pages/Partnerships')),
    "PitchDeckBuilder": lazy(() => import('./pages/PitchDeckBuilder')),
    "PlatformOverview": lazy(() => import('./pages/PlatformOverview')),
    "SequenceBuilder": lazy(() => import('./pages/SequenceBuilder')),
    "Settings": lazy(() => import('./pages/Settings')),
    "SimulationEngine": lazy(() => import('./pages/SimulationEngine')),
    "SubscriptionManagement": lazy(() => import('./pages/SubscriptionManagement')),
    "SystemArchitecture": lazy(() => import('./pages/SystemArchitecture')),
    "SystemHealth": lazy(() => import('./pages/SystemHealth')),
    "TalentAnalytics": lazy(() => import('./pages/TalentAnalytics')),
    "TalentDiscovery": lazy(() => import('./pages/TalentDiscovery')),
    "TalentProfile": lazy(() => import('./pages/TalentProfile')),
    "TalentRevenue": lazy(() => import('./pages/TalentRevenue')),
    "Teams": lazy(() => import('./pages/Teams')),
    "TalentDataRoom": lazy(() => import('./pages/TalentDataRoom')),
    "BrandDataRoom": lazy(() => import('./pages/BrandDataRoom')),
    "AgencyDataRoom": lazy(() => import('./pages/AgencyDataRoom')),
    "BrandSpendPrediction": lazy(() => import('./pages/BrandSpendPrediction')),
    "CreatorCalculator": lazy(() => import('./pages/CreatorCalculator')),
    "WarmIntroNetwork": lazy(() => import('./pages/WarmIntroNetwork')),
    "PitchCompetition": lazy(() => import('./pages/PitchCompetition')),
    "BundleDeals": lazy(() => import('./pages/BundleDeals')),
    "DealComparison": lazy(() => import('./pages/DealComparison')),
    "ContractTemplates": lazy(() => import('./pages/ContractTemplates')),
    "Referrals": lazy(() => import('./pages/Referrals')),
    "DeckLibrary": lazy(() => import('./pages/DeckLibrary')),
    "About": lazy(() => import('./pages/About')),
    "Blog": lazy(() => import('./pages/Blog')),
    "Careers": lazy(() => import('./pages/Careers')),
    "Contact": lazy(() => import('./pages/Contact')),
    "Customers": lazy(() => import('./pages/Customers')),
    "CookiePolicy": lazy(() => import('./pages/CookiePolicy')),
    "GDPR": lazy(() => import('./pages/GDPR')),
    "Demo": lazy(() => import('./pages/Demo')),
    "ManagerSetup": lazy(() => import('./pages/ManagerSetup')),
    "ManagerProfile": lazy(() => import('./pages/ManagerProfile')),
};

export { PAGES };

export const pagesConfig = {
    mainPage: "Dashboard",
    Pages: PAGES,
    Layout: __Layout,
};
